// stores/storeConfigs.ts
import { Categories, StoreConfig } from "../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const colors = ["Black", "Silver", "White"];
const renegadeColors = ["Black", "Gray", "Purple"];
const materials = ["Cotton", DRIFIT];
const backMock = "hustleNational/Back_mock.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const stores: Record<string, StoreConfig> = {
  store1: {
    id: 1,
    version: 1,
    name: "Store 1",
    branding: {
      logo: "/store1-logo.png",
      primaryColor: "#ff5733",
      secondaryColor: "#c70039",
    },
    passcode: "s1",
    players: [
      { name: "John Doe", number: "10" },
      { name: "Jane Smith", number: "12" },
      { name: "Mike Johnson", number: "8" },
    ],
    items: [
      {
        id: 1,
        title: "T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 19.99,
        image: "/tshirt.png",
        sizes: ["S", "M", "L", "XL"],
        colors,
        material: [...materials],
        orders: [],
      },
      {
        id: 2,
        title: "Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 22.99,
        image: "/tshirt.png",
        sizes: ["S", "M", "L", "XL"],
        colors,
        material: [...materials],
        orders: [],
      },
      // More items...
    ],
  },
  renegades: {
    id: 2,
    version: 1,
    name: "renegades",
    branding: {
      logo: "",
      primaryColor: "#ffffff",
      secondaryColor: "#39c7c7",
    },
    players: [
      { name: "Arabella Martinez", number: "00" },
      { name: "Landree Kenney", number: "2" },
      { name: "Chloe Lizardi", number: "3" },
      { name: "Ashlyn Thomas", number: "4" },
      { name: "Eliana Ortega", number: "5" },
      { name: "Kaylee Cabrera", number: "9" },
      { name: "Sloane Rencurel", number: "17" },
      { name: "Ilyana Garcia", number: "19" },
      { name: "Avery Turner", number: "21" },
      { name: "Everly Dawson", number: "25" },
      { name: "Johanna Cox", number: "33" },
      { name: "Mya Villaloboz", number: "88" },
      coach,
    ],
    passcode: "ren",
    items: [
      {
        id: 2,
        title: "Leopard Fastpitch T-Shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/12-purple-leopard-front.png",
        backImage: backMock,
        images: [
          {
            id: 2,
            imageUrl: "renegades/12-purple-leopard-front.png",
            color: "purple",
          },
          {
            id: 0,
            imageUrl: "renegades/12-black-leopard-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/12-gray-leopard-front.png",
            color: "gray",
          },
        ],
        sizes: allSizes,
        colors: [...renegadeColors],
        material: [...materials],
        orders: [],
      },
      {
        id: 7,
        title: "Little Brother Big Fan T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/11-black-SisBro-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/11-black-SisBro-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/11-purple-SisBro-front.png",
            color: "purple",
          },
          {
            id: 4,
            imageUrl: "renegades/11-silver-SisBro-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/11-purple-SisBro-boy-mock.png",
            color: "black",
          },
          {
            id: 3,
            imageUrl: "renegades/11-purple-SisBro-girl-mock.png",
            color: "purple",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Purple", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 8,
        title: "Little Brother Big Fan Hoodie - Customizable",
        isCustomizable: true,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/11-black-SisBro-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/11-black-SisBro-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 9,
        title: "My Favorite Player T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/13-black-customHeart-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/13-black-customHeart-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/13-purple-customHeart-front.png",
            color: "purple",
          },
          {
            id: 1,
            imageUrl: "renegades/13-gray-customHeart-front.png",
            color: "gray",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Purple", "Gray"],
        material: [...materials],
        orders: [],
      },
      {
        id: 10,
        title: "Renegade Dad T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/14-gray-dad-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/14-gray-dad-front.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/14-black-dad-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/14-silver-dad-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Gray", "Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 11,
        title: "Renegade Dad Hoodie - Customizable",
        isCustomizable: true,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/14-black-dad-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/14-black-dad-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 12,
        title: "Renegade Mom T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/15-white-customMom-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/15-white-customMom-front.png",
            color: "white",
          },
          {
            id: 2,
            imageUrl: "renegades/15-black-customMom-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/15-silver-customMom-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 4,
        title: "Traditional Purple TX Softball T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/1-black-purple-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/1-black-purple-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/1-Black-+Purple-Back.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/1-Blue-Purple-front.png",
            color: "teal",
          },
          {
            id: 3,
            imageUrl: "renegades/1-Blue-Purple-Back.png",
            color: "teal",
          },
          {
            id: 4,
            imageUrl: "renegades/1-white-purple-front.png",
            color: "silver",
          },
          {
            id: 5,
            imageUrl: "renegades/1-white-purple-back.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Silver", "Teal"],
        material: [...materials],
        orders: [],
      },
      {
        id: 3,
        title: "TX Renegades T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/10-silver-TexRen-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/10-silver-TexRen-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/10-black-TexRen-front.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 5,
        title: "TX Renegades Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/10-black-TexRen-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/10-black-TexRen-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 6,
        title: "TX Renegades Crop Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/10-black-TexRen-crop top hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/10-black-TexRen-crop top hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 14,
        title: "Traditional Blue TX Softball T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/2-purple-blue-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/2-purple-blue-front.png",
            color: "purple",
          },
          {
            id: 1,
            imageUrl: "renegades/2-purple-blue-back.png",
            color: "purple",
          },
          {
            id: 2,
            imageUrl: "renegades/2-black-blue-front.png",
            color: "black",
          },
          {
            id: 3,
            imageUrl: "renegades/2-black-blue-back.png",
            color: "black",
          },
          {
            id: 4,
            imageUrl: "renegades/2-white-blue-front.png",
            color: "white",
          },
          {
            id: 5,
            imageUrl: "renegades/2-white-blue-back.png",
            color: "white",
          },
        ],
        sizes: allSizes,
        colors: ["Purple", "Black", "White"],
        material: [...materials],
        orders: [],
      },
      {
        id: 15,
        title: "Renegade Fastpitch T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/3-black-fastpitch-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/3-black-fastpitch-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/3-gray-fastpitch-front.png",
            color: "gray",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: [...materials],
        orders: [],
      },
      {
        id: 17,
        title: "Retro T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/4-gray-retro-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/4-gray-retro-front.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/4-black-retro-front.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: [...materials],
        orders: [],
      },
      {
        id: 16,
        title: "Renegade Fastpitch Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/3-black-fastpitch-+Hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/3-black-fastpitch-+Hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 18,
        title: "Retro Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/4-black-retro-+hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/4-black-retro-+hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 19,
        title: "Play Like a Renegade T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/5-silver-play-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/5-silver-play-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/5-black-play-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/5-white-play-front.png",
            color: "white",
          },
        ],
        sizes: allSizes,
        colors: ["Silver", "Black", "White"],
        material: [...materials],
        orders: [],
      },
      {
        id: 20,
        title: "Play Like a Renegade Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/5-black-play-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/5-black-play-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 21,
        title: "Play Block T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/6-white-simple-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/6-white-simple-front.png",
            color: "white",
          },
          {
            id: 1,
            imageUrl: "renegades/6-black-simple-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/6-silver-simple-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 22,
        title: "Play Block Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/6-black-simple-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/6-black-simple-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 23,
        title: "Take T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/7-black-take-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/7-black-take-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/7-white-take-front.png",
            color: "white",
          },
          {
            id: 2,
            imageUrl: "renegades/7-silver-take-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "White", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 24,
        title: "Take Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/7-black-take-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/7-black-take-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 25,
        title: "Texas State T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/8-silver-texas-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/8-silver-texas-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/8-black-texas-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/8-white-texas-front.png",
            color: "white",
          },
        ],
        sizes: allSizes,
        colors: ["Silver", "Black", "White"],
        material: [...materials],
        orders: [],
      },
      {
        id: 26,
        title: "Texas State Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/8-black-texas-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/8-black-texas-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 27,
        title: "Texas Block T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/9-blue-block-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/9-blue-block-front.png",
            color: "blue",
          },
          {
            id: 1,
            imageUrl: "renegades/9-gray-block-front.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/9-silver-block-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Blue", "Gray", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 28,
        title: "Renegades Cotton Jersey T-Shirt",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "renegades/17-Black+Jersey+Shirt-+Renegade+Logo-Front.png",
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/17-Black+Jersey+Shirt-+Renegade+Logo-Front.png",
            color: "Black/Gray",
          },
          {
            id: 1,
            imageUrl: "renegades/17-Black+Jersey+Shirt-+Renegade+Logo-Back.png",
            color: "Black/Gray",
          },
        ],
        sizes: ["XS", "S", "M", "L", "XL", "2XL"],
        colors: ["Black/Gray"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 29,
        title: "Texas Renegades Womens Tri-blend Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image:
          "renegades/18-+Womens+Gray+Jersey+Shirt-+Texas+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/18-+Womens+Gray+Jersey+Shirt-+Texas+Renegade-Front.png",
            color: "Gray/Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Gray/Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 30,
        title: "Retro Womens Tri-blend Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/19-+Womens+Gray+Jersey+Shirt-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/19-+Womens+Gray+Jersey+Shirt-+Retro-Front.png",
            color: "Gray/White Sleeve",
          },
          {
            id: 1,
            imageUrl:
              "renegades/19-+Womens+Black+Jersey+Shirt-+Retro-Front.png",
            color: "Black/Gray Sleeve",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Gray/White Sleeve", "Black/Gray Sleeve"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 31,
        title: "Take Womens Tri-blend Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/20-+Womens+Black+Jersey+Shirt-+Take-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/20-+Womens+Black+Jersey+Shirt-+Take-Front.png",
            color: "Black/Gray Sleeve",
          },
          {
            id: 1,
            imageUrl: "renegades/20-+Womens+Gray+Jersey+Shirt-+Take-Front.png",
            color: "Gray/Black Sleeve",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black/Gray Sleeve", "Gray/Black Sleeve"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 32,
        title: "Traditional Blue Logo Drifit Henley",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 30.0,
        image: "renegades/21-+Henley's+Black+Shirt-+blue-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/21-+Henley's+Black+Shirt-+blue-Front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/21-+Henley's+Purple+Shirt-+blue-Front.png",
            color: "Purple",
          },
        ],
        sizes: ["S", "M", "XL", "2XL", "3XL"],
        colors: ["Black", "Purple"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 33,
        title: "Take Womens Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "renegades/23-+Womens+Black+Short+Sleeve+Shirt-+Take-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/23-+Womens+Black+Short+Sleeve+Shirt-+Take-Front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/23-+Womens+White+Short+Sleeve+Shirt-+Take-Front.png",
            color: "white",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 34,
        title: "Retro Womens Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/24-+Womens+Purple+Short+Sleeve+Shirt-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/24-+Womens+Purple+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Purple",
          },
          {
            id: 1,
            imageUrl:
              "renegades/24-+Womens+Black+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Purple", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 35,
        title: "Texas Renegades Womens Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/25-+Womens+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/25-+Womens+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "renegades/25-+Womens+Black+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 36,
        title: "Retro Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "renegades/26-+Gray+Short+Sleeve+Shirt-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/26-+Gray+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "renegades/26-+Black+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Gray", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 37,
        title: "Texas Renegades Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/27-+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/27-+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "renegades/27-+Black+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl:
              "renegades/27-+Gray+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "Gray",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["White", "Black", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 38,
        title: "Take Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/28-+Black+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/28-+Black+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/28-+White+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
            color: "White",
          },
          {
            id: 2,
            imageUrl:
              "renegades/28-+Gray+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
            color: "Gray",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "White", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 39,
        title: "Traditional Blue Quarter Zip Long Sleeve Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/29-+Black+Quarter+Zipper+Long+Sleeve-+Blue-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/29-+Black+Quarter+Zipper+Long+Sleeve-+Blue-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/29-+White+Quarter+Zipper+Long+Sleeve-+Blue-Front.png",
            color: "White",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 40,
        title: "Traditional Purple Quarter Zip Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image:
          "renegades/30-+White+Quarter+Zipper+Long+Sleeve-+Purple-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/30-+Black+Quarter+Zipper+Long+Sleeve-+Purple-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/30-+White+Quarter+Zipper+Long+Sleeve-+Purple-Front.png",
            color: "White",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 41,
        title: "Retro Drifit Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/31-+Black+Long+Sleeve-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/31-+Black+Long+Sleeve-+Retro-Front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 42,
        title: "Take Drifit Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/32-+white+Long+Sleeve-+Take-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/32-+white+Long+Sleeve-+Take-Front.png",
            color: "white",
          },
          {
            id: 1,
            imageUrl: "renegades/32-+Black+Long+Sleeve-+Take-Front.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 43,
        title: "Texas Renegades Drifit Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/33-+Black+Long+Sleeve-+Texas+Renegades-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/33-+Black+Long+Sleeve-+Texas+Renegades-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/33-+White+Long+Sleeve-+Texas+Renegades-Front.png",
            color: "White",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 13,
        title: "Renegade Joggers",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 30.0,
        image: "renegades/16-black-joggers.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/16-black-joggers.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/16-gray-joggers.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/16-gray-joggers-girl-mock.png",
            color: "gray",
          },
        ],
        sizes: [...youthSizes, "S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "Gray"],
        material: ["Cotton"],
        orders: [],
      },
      // More items...
    ],
  },
  hustle: {
    id: 3,
    version: 4,
    name: "HUSTLE",
    branding: {
      logo: "",
      primaryColor: "#ffffff",
      secondaryColor: "#00C0C0",
    },
    players: [
      { name: "Sophia Ramirez", number: "10" },
      { name: "Jane Smith", number: "12" },
      { name: "Mike Johnson", number: "8" },
    ],
    passcode: "national",
    items: [
      {
        id: 1,
        title: "Paint Strokes",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/Paint_HN_black.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/Paint_HN_black.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/paint_HN_Silver.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 2,
        title: "Born to Hustle",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/bornToHustle_WhiteTeal_black.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/bornToHustle_WhiteTeal_black.png",
            color: "black",
          },
          {
            id: 0,
            imageUrl: "hustleNational/bornToHustle_Silver.png",
            color: "silver",
          },
        ],
        sizes,
        colors: ["Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 3,
        title: "Respect Hustle",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/respectTheHustle_silver.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/respectTheHustle_silver.png",
            color: "silver",
          },
          {
            id: 0,
            imageUrl: "hustleNational/respectTheHustle_black.png",
            color: "black",
          },
        ],
        sizes,
        colors: ["Black", "Silver"],
        material: [...materials],
        orders: [],
      },
    ],
  },
  // Add more stores as needed...
};
