// stores/storeConfigs.ts
import { Categories, StoreConfig } from "../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const colors = ["Black", "Silver", "White"];
const renegadeColors = ["Black", "Gray", "Purple"];
const materials = ["Cotton", DRIFIT];
const backMock = "hustleNational/Back_mock.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const stores: Record<string, StoreConfig> = {
  store1: {
    id: 1,
    version: 1,
    name: "Store 1",
    branding: {
      logo: "/store1-logo.png",
      primaryColor: "#ff5733",
      secondaryColor: "#c70039",
    },
    passcode: "s1",
    players: [
      { name: "John Doe", number: "10" },
      { name: "Jane Smith", number: "12" },
      { name: "Mike Johnson", number: "8" },
    ],
    items: [
      {
        id: 1,
        title: "T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 19.99,
        image: "/tshirt.png",
        sizes: ["S", "M", "L", "XL"],
        colors,
        material: [...materials],
        orders: [],
      },
      {
        id: 2,
        title: "Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 22.99,
        image: "/tshirt.png",
        sizes: ["S", "M", "L", "XL"],
        colors,
        material: [...materials],
        orders: [],
      },
      // More items...
    ],
  },
  renegades: {
    id: 2,
    version: 2,
    name: "renegades",
    branding: {
      logo: "",
      primaryColor: "#ffffff",
      secondaryColor: "#39c7c7",
    },
    players: [
      { name: "Arabella Martinez", number: "00" },
      { name: "Landree Kenney", number: "2" },
      { name: "Chloe Lizardi", number: "3" },
      { name: "Ashlyn Thomas", number: "4" },
      { name: "Eliana Ortega", number: "5" },
      { name: "Kaylee Cabrera", number: "9" },
      { name: "Sloane Rencurel", number: "17" },
      { name: "Ilyana Garcia", number: "19" },
      { name: "Avery Turner", number: "21" },
      { name: "Everly Dawson", number: "25" },
      { name: "Johanna Cox", number: "33" },
      { name: "Mya Villaloboz", number: "88" },
      coach,
    ],
    passcode: "ren",
    items: [
      {
        id: 2,
        title: "Leopard Fastpitch T-Shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/12-purple-leopard-front.png",
        backImage: backMock,
        images: [
          {
            id: 2,
            imageUrl: "renegades/12-purple-leopard-front.png",
            color: "purple",
          },
          {
            id: 0,
            imageUrl: "renegades/12-black-leopard-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/12-gray-leopard-front.png",
            color: "gray",
          },
        ],
        sizes: allSizes,
        colors: [...renegadeColors],
        material: [...materials],
        orders: [],
      },
      {
        id: 7,
        title: "Little Brother Big Fan T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/11-black-SisBro-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/11-black-SisBro-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/11-purple-SisBro-front.png",
            color: "purple",
          },
          {
            id: 4,
            imageUrl: "renegades/11-silver-SisBro-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/11-purple-SisBro-boy-mock.png",
            color: "black",
          },
          {
            id: 3,
            imageUrl: "renegades/11-purple-SisBro-girl-mock.png",
            color: "purple",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Purple", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 8,
        title: "Little Brother Big Fan Hoodie - Customizable",
        isCustomizable: true,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/11-black-SisBro-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/11-black-SisBro-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 9,
        title: "My Favorite Player T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/13-black-customHeart-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/13-black-customHeart-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/13-purple-customHeart-front.png",
            color: "purple",
          },
          {
            id: 1,
            imageUrl: "renegades/13-gray-customHeart-front.png",
            color: "gray",
          },
        ],
        sizes,
        colors: ["Black", "Purple", "Gray"],
        material: [...materials],
        orders: [],
      },
      {
        id: 10,
        title: "Renegade Dad T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/14-gray-dad-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/14-gray-dad-front.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/14-black-dad-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/14-silver-dad-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Gray", "Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 11,
        title: "Renegade Dad Hoodie - Customizable",
        isCustomizable: true,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/14-black-dad-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/14-black-dad-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 12,
        title: "Renegade Mom T-shirt - Customizable",
        isCustomizable: true,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/15-white-customMom-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/15-white-customMom-front.png",
            color: "white",
          },
          {
            id: 2,
            imageUrl: "renegades/15-black-customMom-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/15-silver-customMom-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 4,
        title: "Traditional Purple TX Softball T-Shirt",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/1-black-purple-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/1-black-purple-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/1-Black-+Purple-Back.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/1-Blue-Purple-front.png",
            color: "teal",
          },
          {
            id: 3,
            imageUrl: "renegades/1-Blue-Purple-Back.png",
            color: "teal",
          },
          {
            id: 4,
            imageUrl: "renegades/1-white-purple-front.png",
            color: "silver",
          },
          {
            id: 5,
            imageUrl: "renegades/1-white-purple-back.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Silver", "Teal"],
        material: [...materials],
        orders: [],
      },
      {
        id: 3,
        title: "TX Renegades T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/10-silver-TexRen-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/10-silver-TexRen-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/10-black-TexRen-front.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 5,
        title: "TX Renegades Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/10-black-TexRen-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/10-black-TexRen-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 6,
        title: "TX Renegades Crop Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/10-black-TexRen-crop top hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/10-black-TexRen-crop top hoodie.png",
            color: "black",
          },
        ],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 14,
        title: "Traditional Blue TX Softball T-Shirt",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/2-purple-blue-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/2-purple-blue-front.png",
            color: "purple",
          },
          {
            id: 1,
            imageUrl: "renegades/2-purple-blue-back.png",
            color: "purple",
          },
          {
            id: 2,
            imageUrl: "renegades/2-black-blue-front.png",
            color: "black",
          },
          {
            id: 3,
            imageUrl: "renegades/2-black-blue-back.png",
            color: "black",
          },
          {
            id: 4,
            imageUrl: "renegades/2-white-blue-front.png",
            color: "white",
          },
          {
            id: 5,
            imageUrl: "renegades/2-white-blue-back.png",
            color: "white",
          },
        ],
        sizes: allSizes,
        colors: ["Purple", "Black", "White"],
        material: [...materials],
        orders: [],
      },
      {
        id: 15,
        title: "Renegade Fastpitch T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/3-black-fastpitch-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/3-black-fastpitch-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/3-gray-fastpitch-front.png",
            color: "gray",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: [...materials],
        orders: [],
      },
      {
        id: 17,
        title: "Retro T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/4-gray-retro-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/4-gray-retro-front.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/4-black-retro-front.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: [...materials],
        orders: [],
      },
      {
        id: 16,
        title: "Renegade Fastpitch Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/3-black-fastpitch-+Hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/3-black-fastpitch-+Hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 18,
        title: "Retro Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/4-black-retro-+hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/4-black-retro-+hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 19,
        title: "Play Like a Renegade T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/5-silver-play-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/5-silver-play-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/5-black-play-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/5-white-play-front.png",
            color: "white",
          },
        ],
        sizes: allSizes,
        colors: ["Silver", "Black", "White"],
        material: [...materials],
        orders: [],
      },
      {
        id: 20,
        title: "Play Like a Renegade Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/5-black-play-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/5-black-play-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 21,
        title: "Play Block T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/6-white-simple-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/6-white-simple-front.png",
            color: "white",
          },
          {
            id: 1,
            imageUrl: "renegades/6-black-simple-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/6-silver-simple-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 22,
        title: "Play Block Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/6-black-simple-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/6-black-simple-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 23,
        title: "Take T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/7-black-take-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/7-black-take-front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/7-white-take-front.png",
            color: "white",
          },
          {
            id: 2,
            imageUrl: "renegades/7-silver-take-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "White", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 24,
        title: "Take Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/7-black-take-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/7-black-take-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 25,
        title: "Texas State T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/8-silver-texas-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/8-silver-texas-front.png",
            color: "silver",
          },
          {
            id: 1,
            imageUrl: "renegades/8-black-texas-front.png",
            color: "black",
          },
          {
            id: 2,
            imageUrl: "renegades/8-white-texas-front.png",
            color: "white",
          },
        ],
        sizes: allSizes,
        colors: ["Silver", "Black", "White"],
        material: [...materials],
        orders: [],
      },
      {
        id: 26,
        title: "Texas State Hoodie",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/8-black-texas-hoodie.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/8-black-texas-hoodie.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 27,
        title: "Texas Block T-shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "renegades/9-blue-block-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/9-blue-block-front.png",
            color: "blue",
          },
          {
            id: 1,
            imageUrl: "renegades/9-gray-block-front.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/9-silver-block-front.png",
            color: "silver",
          },
        ],
        sizes: allSizes,
        colors: ["Blue", "Gray", "Silver"],
        material: [...materials],
        orders: [],
      },
      {
        id: 28,
        title: "Renegades Cotton Jersey T-Shirt",
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        showBackSelection: false,
        image: "renegades/17-Black+Jersey+Shirt-+Renegade+Logo-Front.png",
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/17-Black+Jersey+Shirt-+Renegade+Logo-Front.png",
            color: "Black/Gray",
          },
          {
            id: 1,
            imageUrl: "renegades/17-Black+Jersey+Shirt-+Renegade+Logo-Back.png",
            color: "Black/Gray",
          },
        ],
        sizes: ["XS", "S", "M", "L", "XL", "2XL"],
        colors: ["Black/Gray"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 33,
        title: "Take Womens Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "renegades/23-+Womens+Black+Short+Sleeve+Shirt-+Take-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/23-+Womens+Black+Short+Sleeve+Shirt-+Take-Front.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/23-+Womens+White+Short+Sleeve+Shirt-+Take-Front.png",
            color: "white",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 34,
        title: "Retro Womens Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/24-+Womens+Purple+Short+Sleeve+Shirt-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/24-+Womens+Purple+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Purple",
          },
          {
            id: 1,
            imageUrl:
              "renegades/24-+Womens+Black+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Purple", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 35,
        title: "Texas Renegades Womens Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/25-+Womens+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/25-+Womens+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "renegades/25-+Womens+Black+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 36,
        title: "Retro Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "renegades/26-+Gray+Short+Sleeve+Shirt-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/26-+Gray+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "renegades/26-+Black+Short+Sleeve+Shirt-+Retro-Front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Gray", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 37,
        title: "Texas Renegades Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/27-+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/27-+White+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "renegades/27-+Black+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl:
              "renegades/27-+Gray+Short+Sleeve+Shirt-+Texas+Renegade-Front.png",
            color: "Gray",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["White", "Black", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 38,
        title: "Take Drifit Muscle T-Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image:
          "renegades/28-+Black+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/28-+Black+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/28-+White+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
            color: "White",
          },
          {
            id: 2,
            imageUrl:
              "renegades/28-+Gray+Short+Sleeve+Shirt-+Take+Renegade-Front.png",
            color: "Gray",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "White", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 39,
        title: "Traditional Blue Quarter Zip Long Sleeve Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/29-+Black+Quarter+Zipper+Long+Sleeve-+Blue-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/29-+Black+Quarter+Zipper+Long+Sleeve-+Blue-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/29-+White+Quarter+Zipper+Long+Sleeve-+Blue-Front.png",
            color: "White",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 40,
        title: "Traditional Purple Quarter Zip Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image:
          "renegades/30-+White+Quarter+Zipper+Long+Sleeve-+Purple-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/30-+Black+Quarter+Zipper+Long+Sleeve-+Purple-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/30-+White+Quarter+Zipper+Long+Sleeve-+Purple-Front.png",
            color: "White",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 41,
        title: "Retro Drifit Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/31-+Black+Long+Sleeve-+Retro-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/31-+Black+Long+Sleeve-+Retro-Front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 42,
        title: "Take Drifit Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/32-+white+Long+Sleeve-+Take-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "renegades/32-+white+Long+Sleeve-+Take-Front.png",
            color: "white",
          },
          {
            id: 1,
            imageUrl: "renegades/32-+Black+Long+Sleeve-+Take-Front.png",
            color: "black",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 43,
        title: "Texas Renegades Drifit Long Sleeve T-Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "renegades/33-+Black+Long+Sleeve-+Texas+Renegades-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "renegades/33-+Black+Long+Sleeve-+Texas+Renegades-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "renegades/33-+White+Long+Sleeve-+Texas+Renegades-Front.png",
            color: "White",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 13,
        title: "Renegade Joggers",
        isCustomizable: false,
        category: Categories.BOTTOMS,
        price: 30.0,
        showBackSelection: false,
        image: "renegades/16-black-joggers.png",
        images: [
          {
            id: 0,
            imageUrl: "renegades/16-black-joggers.png",
            color: "black",
          },
          {
            id: 1,
            imageUrl: "renegades/16-gray-joggers.png",
            color: "gray",
          },
          {
            id: 2,
            imageUrl: "renegades/16-gray-joggers-girl-mock.png",
            color: "gray",
          },
        ],
        sizes: [...youthSizes, "S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black", "Gray"],
        material: ["Cotton"],
        orders: [],
      },
      // More items...
    ],
  },
  hustle: {
    id: 3,
    version: 4,
    name: "HUSTLE",
    branding: {
      logo: "",
      primaryColor: "#ffffff",
      secondaryColor: "#00C0C0",
    },
    players: [
      { name: "Analina Ramirez", number: "2" },
      { name: "Skylar Ottele", number: "3" },
      { name: "Bree Tucker", number: "7" },
      { name: "Maddi Gonzalez", number: "9" },
      { name: "Kaylee Riddle", number: "10" },
      { name: "Lilee Galvan", number: "13" },
      { name: "Sophia Ramirez", number: "19" },
      { name: "Ellie Kennedy", number: "21" },
      { name: "Mila Reyna", number: "24" },
      { name: "Malaya Dislate", number: "44" },
      { name: "Scarlett Torres", number: "77" },
      { name: "Coach", number: "n/a" },
    ],
    passcode: "national",
    items: [
      {
        id: 1,
        title: "Hustle Jersey Shirt",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 35.0,
        image:
          "hustleNational/1-BlackJerseyShirt-HustleNationalSoftball-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/1-BlackJerseyShirt-HustleNationalSoftball-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl:
              "hustleNational/1-BlackJerseyShirt-HustleNationalSoftball-Back.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/1-NavyJerseyShirt-HustleNationalSoftball-Front.png",
            color: "Navy",
          },
          {
            id: 3,
            imageUrl:
              "hustleNational/1-NavyJerseyShirt-HustleNationalSoftball-Back.png",
            color: "Navy",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black", "Navy"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 2,
        title: "Born to Hustle Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/10-BlueLongSleeve-Born-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/10-BlueLongSleeve-Born-front.png",
            color: "Navy",
          },
          {
            id: 1,
            imageUrl: "hustleNational/10-BlackLongSleeve-Born-front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Navy", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 3,
        title: "Respect the Hustle Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/11-WhiteLongSleeve-Respect-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/11-WhiteLongSleeve-Respect-front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl: "hustleNational/11-BlackLongSleeve-Respect-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/11-BlueLongSleeve-Respect-front.png",
            color: "Navy",
          },
          {
            id: 3,
            imageUrl: "hustleNational/11-SilverLongSleeve-Respect-front.png",
            color: "Silver",
          },
          {
            id: 4,
            imageUrl: "hustleNational/11-GrayLongSleeve-Respect-front.png",
            color: "Gray",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black", "Navy", "Silver", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 4,
        title: "Hustle Paint Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/12-GrayLongSleeve-Paint-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/12-GrayLongSleeve-Paint-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/12-BlackLongSleeve-Paint-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/12-BlueLongSleeve-Paint-front.png",
            color: "Navy",
          },
          {
            id: 3,
            imageUrl: "hustleNational/12-SilverLongSleeve-Paint-front.png",
            color: "Silver",
          },
        ],
        sizes: allSizes,
        colors: ["Gray", "Black", "Navy", "Silver"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 5,
        title: "Lined H Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/13-BlackLongSleeve-LinedH-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/13-BlackLongSleeve-LinedH-front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/13-BlueLongSleeve-LinedH-front.png",
            color: "Navy",
          },
          {
            id: 2,
            imageUrl: "hustleNational/13-SilverLongSleeve-LinedH-front.png",
            color: "Silver",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Navy", "Silver"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 6,
        title: "Hustle National Block Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/14-SilverLongSleeve-HustleBlock-front.png",
        backImage: backMock,
        images: [
          {
            id: 3,
            imageUrl:
              "hustleNational/14-SilverLongSleeve-HustleBlock-front.png",
            color: "Silver",
          },
          {
            id: 0,
            imageUrl: "hustleNational/14-GrayLongSleeve-HustleBlock-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/14-BlackLongSleeve-HustleBlock-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/14-BlueLongSleeve-HustleBlock-front.png",
            color: "Navy",
          },
        ],
        sizes: allSizes,
        colors: ["Silver", "Gray", "Black", "Navy"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 7,
        title: "Hustle Half Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/15-BlueLongSleeve-Half-front.png",
        backImage: backMock,
        images: [
          {
            id: 1,
            imageUrl: "hustleNational/15-BlueLongSleeve-Half-front.png",
            color: "Navy",
          },
          {
            id: 2,
            imageUrl: "hustleNational/15-WhiteLongSleeve-Half-front.png",
            color: "White",
          },
          {
            id: 0,
            imageUrl: "hustleNational/15-BlackLongSleeve-Half-front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Navy", "White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 8,
        title: "Hustle Plate Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/16-WhiteLongSleeve-HustlePlate-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/16-WhiteLongSleeve-HustlePlate-front.png",
            color: "White",
          },
          {
            id: 3,
            imageUrl:
              "hustleNational/16-SilverLongSleeve-HustlePlate-front.png",
            color: "Silver",
          },
          {
            id: 1,
            imageUrl: "hustleNational/16-BlackLongSleeve-HustlePlate-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/16-BlueLongSleeve-HustlePlate-front.png",
            color: "Navy",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Silver", "Black", "Navy"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 9,
        title: "Hustle Flag Long Sleeve",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 25.0,
        image: "hustleNational/9-BlackLongSleeve-Flag-front.png",
        backImage: backMock,
        images: [
          {
            id: 1,
            imageUrl: "hustleNational/9-BlackLongSleeve-Flag-front.png",
            color: "Black",
          },
          {
            id: 0,
            imageUrl: "hustleNational/9-BlueLongSleeve-Flag-front.png",
            color: "Navy",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Navy"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 10,
        title: "Hustle Flag Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/17-BlackHoodedLongSleeve-Flag-front.png",
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/17-BlackHoodedLongSleeve-Flag-front.png",
            color: "Black",
          },
        ],
        sizes: sizes,
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 11,
        title: "Lined H Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/18-BlackHoodedLongSleeve-LinedH-front.png",
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/18-BlackHoodedLongSleeve-LinedH-front.png",
            color: "Black",
          },
        ],
        sizes: sizes,
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 12,
        title: "Respect the Hustle Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/19-GrayHoodedLongSleeve-Respect-front.png",
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/19-GrayHoodedLongSleeve-Respect-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/19-BlackHoodedLongSleeve-Respect-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl:
              "hustleNational/19-WhiteHoodedLongSleeve-Respect-front.png",
            color: "White",
          },
        ],
        sizes: sizes,
        colors: ["Gray", "Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 13,
        title: "Hustle Paint Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/20-BlackHoodedLongSleeve-Paint-front.png",
        images: [
          {
            id: 1,
            imageUrl: "hustleNational/20-BlackHoodedLongSleeve-Paint-front.png",
            color: "Black",
          },
          {
            id: 0,
            imageUrl: "hustleNational/20-GrayHoodedLongSleeve-Paint-front.png",
            color: "Gray",
          },
        ],
        sizes: sizes,
        colors: ["Black", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 14,
        title: "Hustle National Block Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/21-GrayHoodedLongSleeve-HustleBlock-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/21-GrayHoodedLongSleeve-HustleBlock-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/21-BlackHoodedLongSleeve-HustleBlock-front.png",
            color: "Black",
          },
        ],
        sizes: sizes,
        colors: ["Gray", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 15,
        title: "Hustle Plate Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/22-WhiteHoodedLongSleeve-HustlePlate-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/22-WhiteHoodedLongSleeve-HustlePlate-front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/22-BlackHoodedLongSleeve-HustlePlate-front.png",
            color: "Black",
          },
        ],
        sizes: sizes,
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 16,
        title: "Hustle Half Long Sleeve with Hood",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 25.0,
        image: "hustleNational/23-BlackHoodedLongSleeve-Half-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/23-BlackHoodedLongSleeve-Half-front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/23-WhiteHoodedLongSleeve-Half-front.png",
            color: "White",
          },
        ],
        sizes: sizes,
        colors: ["Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 17,
        title: "Hustle H Raider Short Sleeve Quarter-Zip",
        isCustomizable: false,
        category: Categories.LONG_SLEEVE,
        price: 60.0,
        image: "hustleNational/26-NavyQuarterZip-H-Front.png",
        backImage: backMock,
        images: [
          {
            id: 2,
            imageUrl: "hustleNational/26-NavyQuarterZip-H-Front.png",
            color: "Navy",
          },
          {
            id: 0,
            imageUrl: "hustleNational/26-BlackQuarterZip-H-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/26-WhiteQuarterZip-H-Front.png",
            color: "White",
          },
        ],
        sizes: sizes,
        colors: ["Navy", "Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 18,
        title: "Born to Hustle Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/32-BlackCropTop-born-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/32-BlackCropTop-born-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/32-BlackCropTop-born-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 19,
        title: "Respect the Hustle Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/30-BlackCropTop-Respect-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/30-BlackCropTop-Respect-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/30-BlackCropTop-Respect-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 20,
        title: "Hustle Paint Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/29-BlackCropTop-Paint-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/29-BlackCropTop-Paint-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/29-BlackCropTop-Paint-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 21,
        title: "Lined H Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/33-BlackCropTop-LinedH-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/33-BlackCropTop-LinedH-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/33-BlackCropTop-LinedH-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 22,
        title: "Hustle National Block Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/31-BlackCropTop-HustleBlock-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/31-BlackCropTop-HustleBlock-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/31-BlackCropTop-HustleBlock-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 23,
        title: "Hustle Half Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/34-BlackCropTop-Half-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/34-BlackCropTop-Half-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/34-BlackCropTop-Half-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 24,
        title: "Hustle Plate Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/28-BlackCropTop-HustlePlate-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/28-BlackCropTop-HustlePlate-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/28-BlackCropTop-HustlePlate-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 25,
        title: "Hustle Flag Crop Top",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 25.0,
        image: "hustleNational/35-BlackCropTop-Flag-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/35-BlackCropTop-Flag-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/35-BlackCropTop-Flag-Mock.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
        colors: ["Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 26,
        title: "Hustle Plate V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/36-WhiteSleevelessWomens-HustlePlate-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/36-WhiteSleevelessWomens-HustlePlate-front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/36-BlackSleevelessWomens-HustlePlate-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 27,
        title: "Respect the Hustle V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/37-WhiteSleevelessWomens-Respect-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/37-WhiteSleevelessWomens-Respect-front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/37-BlackSleevelessWomens-Respect-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 28,
        title: "Hustle Half V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/38-WhiteSleevelessWomens-Half-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/38-WhiteSleevelessWomens-Half-front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl: "hustleNational/38-BlackSleevelessWomens-Half-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["White", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 29,
        title: "Hustle Paint V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/39-BlackSleevelessWomens-Paint-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/39-BlackSleevelessWomens-Paint-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 30,
        title: "Hustle National Block V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/40-BlackSleevelessWomens-HustleBlock-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/40-BlackSleevelessWomens-HustleBlock-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 31,
        title: "Born to Hustle V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/41-BlackSleevelessWomens-Born-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/41-BlackSleevelessWomens-Born-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 32,
        title: "Lined H V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/42-BlackSleevelessWomens-LinedH-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/42-BlackSleevelessWomens-LinedH-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 33,
        title: "Hustle Flag V-Neck Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/43-BlackSleevelessWomens-Flag-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/43-BlackSleevelessWomens-Flag-front.png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 34,
        title: "Hustle Plate Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/44-GraySleeveless-HustlePlate-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/44-GraySleeveless-HustlePlate-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/44-BlackSleeveless-HustlePlate-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/44-WhiteSleeveless-HustlePlate-front.png",
            color: "White",
          },
        ],
        sizes: allSizes,
        colors: ["Gray", "Black", "White"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 35,
        title: "Hustle Flag Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/45-BlackSleeveless-Flag-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/45-BlackSleeveless-Flag-front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/45-GraySleeveless-Flag-front.png",
            color: "Gray",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 36,
        title: "Lined H Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/46-GraySleeveless-LinedH-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/46-GraySleeveless-LinedH-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/46-BlackSleeveless-LinedH-front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Gray", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 37,
        title: "Born to Hustle Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/47-BlackSleeveless-Born-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/47-BlackSleeveless-Born-front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 38,
        title: "Hustle Paint Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/48-GraySleeveless-Paint-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/48-GraySleeveless-Paint-front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/48-BlackSleeveless-Paint-front.png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Gray", "Black"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 39,
        title: "Respect the Hustle Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/49-WhiteSleeveless-Respect-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/49-WhiteSleeveless-Respect-front.png",
            color: "White",
          },
          {
            id: 1,
            imageUrl: "hustleNational/49-BlackSleeveless-Respect-front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/49-GraySleeveless-Respect-front.png",
            color: "Gray",
          },
        ],
        sizes: allSizes,
        colors: ["White", "Black", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 40,
        title: "Hustle National Block Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/50-BlackSleeveless-HustleBlock-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/50-BlackSleeveless-HustleBlock-front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/50-GraySleeveless-HustleBlock-front.png",
            color: "Gray",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 41,
        title: "Hustle Half Sleeveless Shirt",
        isCustomizable: false,
        category: Categories.TSHIRTS,
        price: 20.0,
        image: "hustleNational/51-BlackSleeveless-Half-front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/51-BlackSleeveless-Half-front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/51-WhiteSleeveless-Half-front.png",
            color: "White",
          },
          {
            id: 2,
            imageUrl: "hustleNational/51-GraySleeveless-Half-front.png",
            color: "Gray",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "White", "Gray"],
        material: [DRIFIT],
        orders: [],
      },
      {
        id: 42,
        title: "Hustle Plate Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/52-CamoCropTopHoodie-HustlePlate-Front.png",
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/52-CamoCropTopHoodie-HustlePlate-Front.png",
            color: "Camo",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/52-BlackCropTopHoodie-HustlePlate-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl:
              "hustleNational/52-BlackCropTopHoodie-HustlePlate-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Camo", "Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 43,
        title: "Hustle Paint Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/53-BlackCropTopHoodie-Paint-Front.png",
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/53-BlackCropTopHoodie-Paint-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/53-CamoCropTopHoodie-Paint-Front.png",
            color: "Camo",
          },
          {
            id: 2,
            imageUrl:
              "hustleNational/53-BlackCropTopHoodie-Paint-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Black", "Camo"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 44,
        title: "Respect the Hustle Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/54-GrayCropTopHoodie-Respect-Front.png",
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/54-GrayCropTopHoodie-Respect-Front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/54-BlackCropTopHoodie-Respect-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/54-CamoCropTopHoodie-Respect-Front.png",
            color: "Camo",
          },
          {
            id: 3,
            imageUrl:
              "hustleNational/54-BlackCropTopHoodie-Respect-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Gray", "Black", "Camo"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 45,
        title: "Hustle National Block Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/55-CamoCropTopHoodie-HustleBlock-Front.png",
        images: [
          {
            id: 0,
            imageUrl:
              "hustleNational/55-CamoCropTopHoodie-HustleBlock-Front.png",
            color: "Camo",
          },
          {
            id: 1,
            imageUrl:
              "hustleNational/55-BlackCropTopHoodie-HustleBlock-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl:
              "hustleNational/55-GrayCropTopHoodie-HustleBlock-Front.png",
            color: "Gray",
          },
          {
            id: 3,
            imageUrl:
              "hustleNational/55-BlackCropTopHoodie-HustleBlock-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Camo", "Black", "Gray"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 46,
        title: "Born to Hustle Block Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/56-CamoCropTopHoodie-Born-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/56-CamoCropTopHoodie-Born-Front.png",
            color: "Camo",
          },
          {
            id: 1,
            imageUrl: "hustleNational/56-BlackCropTopHoodie-Born-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/56-BlackCropTopHoodie-Born-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Camo", "Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 47,
        title: "Lined H Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/57-GrayCropTopHoodie-LinedH-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/57-GrayCropTopHoodie-LinedH-Front.png",
            color: "Gray",
          },
          {
            id: 1,
            imageUrl: "hustleNational/57-BlackCropTopHoodie-LinedH-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/57-CamoCropTopHoodie-LinedH-Front.png",
            color: "Camo",
          },
          {
            id: 3,
            imageUrl:
              "hustleNational/57-BlackCropTopHoodie-LinedH-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Gray", "Black", "Camo"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 48,
        title: "Hustle Half Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/58-CamoCropTopHoodie-Half-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/58-CamoCropTopHoodie-Half-Front.png",
            color: "Camo",
          },
          {
            id: 1,
            imageUrl: "hustleNational/58-BlackCropTopHoodie-Half-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/58-BlackCropTopHoodie-Half-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Camo", "Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 49,
        title: "Hustle Flag Crop Top Hoodie",
        showBackSelection: false,
        isCustomizable: false,
        category: Categories.HOODIES,
        price: 35.0,
        image: "hustleNational/59-CamoCropTopHoodie-Flag-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/59-CamoCropTopHoodie-Flag-Front.png",
            color: "Camo",
          },
          {
            id: 1,
            imageUrl: "hustleNational/59-BlackCropTopHoodie-Flag-Front.png",
            color: "Black",
          },
          {
            id: 2,
            imageUrl: "hustleNational/59-BlackCropTopHoodie-Flag-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: ["S", "M", "L", "XL", "2XL"],
        colors: ["Camo", "Black"],
        material: ["Cotton"],
        orders: [],
      },
      {
        id: 50,
        title: "Hustle Joggers",
        isCustomizable: false,
        showBackSelection: false,
        category: Categories.BOTTOMS,
        price: 35.0,
        image: "hustleNational/60-BlackJoggers-Front.png",
        backImage: backMock,
        images: [
          {
            id: 0,
            imageUrl: "hustleNational/60-BlackJoggers-Front.png",
            color: "Black",
          },
          {
            id: 1,
            imageUrl: "hustleNational/60-GrayJoggers-Front.png",
            color: "Gray",
          },
          {
            id: 2,
            imageUrl: "hustleNational/60-BlackJoggers-Front+(2).png",
            color: "Black",
          },
        ],
        sizes: allSizes,
        colors: ["Black", "Gray"],
        material: ["Cotton"],
        orders: [],
      },
    ],
  },
  // Add more stores as needed...
};
