import { Categories } from "../../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const materials = ["Cotton", DRIFIT];
const backMock = "reign/SHIRTBACK.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const cinco = {
  id: 4,
  version: 1,
  name: "CINCO RANCH",
  branding: {
    logo: "",
    primaryColor: "#ffffff",
    secondaryColor: "#5c0a15",
  },
  passcode: "cinco",
  players: [
    { name: "Lilly Martin", number: "1" },
    { name: "Eiley Key", number: "3" },
    { name: "Emma Schoeneberg", number: "5" },
    { name: "Kaedyn Maxwell", number: "6" },
    { name: "Elle Wallace", number: "8" },
    { name: "Gianna Campise", number: "9" },
    { name: "Lindsey Deleon", number: "10" },
    { name: "Sydni Vandeventer", number: "12" },
    { name: "Aubrey Ramirez", number: "13" },
    { name: "Makenzie McCowan", number: "14" },
    { name: "Savannah Penny", number: "15" },
    { name: "Sophie Hassall", number: "16" },
    { name: "Gaby Perez", number: "20" },
    { name: "Emory Ortiz", number: "22" },
    { name: "Kyndall Collinsworth", number: "32" },
    { name: "Taylor Oliver", number: "1" },
    { name: "Edeline (Izzy) Richard", number: "2" },
    { name: "Ariana Hernandez", number: "3" },
    { name: "Abigail Blum", number: "4" },
    { name: "Kylie Castorena", number: "5" },
    { name: "Nyalese Fortiz", number: "6" },
    { name: "Emma Talbot", number: "8" },
    { name: "Audrey Wells", number: "9" },
    { name: "Kylie Hernandez", number: "11" },
    { name: "Sovi Hilligiest", number: "16" },
    { name: "Kayla Taylor", number: "17" },
    { name: "Yazmin Yon", number: "18" },
    { name: "Londyn Presley", number: "22" },
    { name: "Coach", number: "n/a" },
  ],
  items: [
    {
      id: 1,
      title: "Varsity Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/VarsityShirt.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/VarsityShirt.png",
          color: "Maroon",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/Varsity-Back-and-Front.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 2,
      title: "Junior Varsity Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/JuniorVarsityShirt.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/JuniorVarsityShirt.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/JV-Back-and-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Gray"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 3,
      title: "Varsity Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/Vasity-Long-Sleeve.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/Vasity-Long-Sleeve.png",
          color: "Maroon",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/Vasity-back-and-front-Long-Sleeve.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 4,
      title: "Junior Varsity Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/JV-Long-Sleeve.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/JV-Long-Sleeve.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/JV-back-and-front-Long-Sleeve.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Gray"],
      material: ["Dri-Fit"],
      orders: [],
    },
  ],
};
