import { Categories } from "../../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const materials = ["Cotton", DRIFIT];
const backMock = "reign/SHIRTBACK.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const cinco = {
  id: 4,
  version: 2,
  name: "CINCO RANCH",
  branding: {
    logo: "",
    primaryColor: "#ffffff",
    secondaryColor: "#5c0a15",
  },
  passcode: "cinco",
  players: [
    { name: "Abigail Blum", number: "4" },
    { name: "Ariana Hernandez", number: "3" },
    { name: "Aubrey Ramirez", number: "13" },
    { name: "Audrey Wells", number: "9" },
    { name: "Edeline (Izzy) Richard", number: "2" },
    { name: "Eiley Key", number: "3" },
    { name: "Elle Wallace", number: "8" },
    { name: "Emma Schoeneberg", number: "5" },
    { name: "Emma Talbot", number: "8" },
    { name: "Emory Ortiz", number: "22" },
    { name: "Gaby Perez", number: "20" },
    { name: "Gianna Campise", number: "9" },
    { name: "Kaedyn Maxwell", number: "6" },
    { name: "Kayla Taylor", number: "17" },
    { name: "Kylie Castorena", number: "5" },
    { name: "Kylie Hernandez", number: "11" },
    { name: "Kyndall Collinsworth", number: "32" },
    { name: "Lilly Martin", number: "1" },
    { name: "Lindsey Deleon", number: "10" },
    { name: "Londyn Presley", number: "22" },
    { name: "Makenzie McCowan", number: "14" },
    { name: "Nyalese Fortiz", number: "6" },
    { name: "Savannah Penny", number: "15" },
    { name: "Sophie Hassall", number: "16" },
    { name: "Sovi Hilligiest", number: "16" },
    { name: "Sydni Vandeventer", number: "12" },
    { name: "Taylor Oliver", number: "1" },
    { name: "Yazmin Yon", number: "18" },
    { name: "Coach", number: "n/a" },
  ],
  items: [
    {
      id: 1,
      title: "Varsity Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/1-MaroonShirt-Varsity-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/1-MaroonShirt-Varsity-Front.png",
          color: "Maroon",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/1-MaroonShirt-Varsity-Front%26Back.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 2,
      title: "Junior Varsity Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/2-GrayShirt-JV-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/2-GrayShirt-JV-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/2-GrayShirt-JV-Front%26Back.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Gray"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 3,
      title: "Varsity Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/3-MaroonLongSleeve-Varsity-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/3-MaroonLongSleeve-Varsity-front.png",
          color: "Maroon",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/3-MaroonLongSleeve-Varsity-front%26back.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 4,
      title: "Junior Varsity Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: true,
      backOptionPrice: 0,
      price: 25.0,
      image: "cinco-Ranch/4-GrayLongSleeve-JV-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/4-GrayLongSleeve-JV-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/4-GrayLongSleeve-JV-front%26back.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Gray"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 5,
      title: "Cougars Surge Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 25.0,
      image: "cinco-Ranch/10-WhiteShirt-CougarsSurge-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/10-WhiteShirt-CougarsSurge-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/10-SilverShirt-CougarsSurge-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 6,
      title: "Cougars Surge Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 30.0,
      image: "cinco-Ranch/11-WhiteLongSleeve-CougarsSurge-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/11-WhiteLongSleeve-CougarsSurge-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/11-SilverLongSleeve-CougarsSurge-front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 7,
      title: "Cougars Surge Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 25.0,
      image: "cinco-Ranch/12-GrayCropTop-CougarsSurge-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/12-GrayCropTop-CougarsSurge-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/12-GrayCropTop-CougarsSurge-Mock.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 8,
      title: "Cougars Surge Crop Top Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/13-GrayCropTopHoodie-CougarsSurge-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/13-GrayCropTopHoodie-CougarsSurge-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/13-GrayCropTopHoodie-CougarsSurge-Mock.png",
          color: "Gray",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 9,
      title: "Cougars Surge Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/14-GrayHoodie-CougarsSurge-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/14-GrayHoodie-CougarsSurge-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 10,
      title: "They Not Like Us Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 25.0,
      image: "cinco-Ranch/5-WhiteShirt-NotLikeUs-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/5-WhiteShirt-NotLikeUs-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/5-SilverShirt-NotLikeUs-Front.png",
          color: "Light Gray",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/5-MaroonShirt-NotLikeUs-Front.png",
          color: "Maroon",
        },
        {
          id: 3,
          imageUrl: "cinco-Ranch/5-DarkGrayShirt-NotLikeUs-Front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Light Gray", "Maroon", "Dark Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 11,
      title: "They Not Like Us Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 30.0,
      image: "cinco-Ranch/6-SilverLongSleeve-NotLikeUs-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/6-SilverLongSleeve-NotLikeUs-front.png",
          color: "Light Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/6-WhiteLongSleeve-NotLikeUs-front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/6-MaroonLongSleeve-NotLikeUs-front.png",
          color: "Maroon",
        },
        {
          id: 3,
          imageUrl: "cinco-Ranch/6-DarkGrayLongSleeve-NotLikeUs-front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Light Gray", "White", "Maroon", "Dark Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 12,
      title: "Cinco Pride Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 25.0,
      image: "cinco-Ranch/7-MaroonShirt-CincoPride-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/7-MaroonShirt-CincoPride-Front.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: materials,
      orders: [],
    },
    {
      id: 13,
      title: "Cinco Pride Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 30.0,
      image: "cinco-Ranch/8-MaroonLongSleeve-CincoPride-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/8-MaroonLongSleeve-CincoPride-front.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: materials,
      orders: [],
    },
    {
      id: 14,
      title: "Cinco Pride Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/9-MaroonHoodie-CincoPride-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/9-MaroonHoodie-CincoPride-Front.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Maroon"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 15,
      title: "Cougars Softball Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 25.0,
      image: "cinco-Ranch/20-DarkGrayShirt-CougarsBall-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/20-DarkGrayShirt-CougarsBall-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/20-SilverShirt-CougarsBall-Front.png",
          color: "Light Gray",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/20-MaroonShirt-CougarsBall-Front.png",
          color: "Maroon",
        },
        {
          id: 3,
          imageUrl: "cinco-Ranch/20-WhiteShirt-CougarsBall-Front.png",
          color: "White",
        },
        {
          id: 4,
          imageUrl: "cinco-Ranch/20-BlackShirt-CougarsBall-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Light Gray", "Maroon", "White", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 16,
      title: "Cougars Softball Long Sleeve Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 30.0,
      image: "cinco-Ranch/21-DarkGrayLongSleeve-CougarsBall-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/21-DarkGrayLongSleeve-CougarsBall-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/21-SilverLongSleeve-CougarsBall-front.png",
          color: "Light Gray",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/21-MaroonLongSleeve-CougarsBall-front.png",
          color: "Maroon",
        },
        {
          id: 3,
          imageUrl: "cinco-Ranch/21-WhiteLongSleeve-CougarsBall-front.png",
          color: "White",
        },
        {
          id: 4,
          imageUrl: "cinco-Ranch/21-BlackLongSleeve-CougarsBall-front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Light Gray", "Maroon", "White", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 17,
      title: "Cougars Softball Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 25.0,
      image: "cinco-Ranch/22-BlackCropTop-CougarsBall-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/22-BlackCropTop-CougarsBall-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/22-GrayCropTop-CougarsBall-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/22-GrayCropTop-CougarsBall-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 18,
      title: "Cougars Softball Crop Top Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/24-CamoCropTopHoodie-CougarsBall-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/24-CamoCropTopHoodie-CougarsBall-Front.png",
          color: "Camouflage",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/24-GrayCropTopHoodie-CougarsBall-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/24-BlackCropTopHoodie-CougarsBall-Front.png",
          color: "Black",
        },
        {
          id: 3,
          imageUrl: "cinco-Ranch/24-BlackCropTopHoodie-CougarsBall-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Camouflage", "Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 19,
      title: "Cougars Softball Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/23-DarkGrayHoodie-CougarsBall-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/23-DarkGrayHoodie-CougarsBall-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/23-GrayHoodie-CougarsBall-Front.png",
          color: "Light Gray",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/23-BlackHoodie-CougarsBall-Front.png",
          color: "Black",
        },
        {
          id: 3,
          imageUrl: "cinco-Ranch/23-MaroonHoodie-CougarsBall-Front.png",
          color: "Maroon",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Light Gray", "Black", "Maroon"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 20,
      title: "Cinco Ranch 1/4 Zip Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 65.0,
      image: "cinco-Ranch/25-MaroonQuarterZip-Cinco-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/25-MaroonQuarterZip-Cinco-Front.png",
          color: "Maroon",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/25-WhiteQuarterZip-Cinco-Front.png",
          color: "White",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Maroon", "White"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 21,
      title: "Cinco Ranch Fleece Quarter-Zip Sweatshirt",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/26-BlackFleeceQuarter-zipSweatshirt-Cinco-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "cinco-Ranch/26-BlackFleeceQuarter-zipSweatshirt-Cinco-front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl:
            "cinco-Ranch/26-GrayFleeceQuarter-zipSweatshirt-Cinco-front.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 22,
      title: "Cinco Ranch Full Zip Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 35.0,
      image: "cinco-Ranch/27-MaroonZipUpHoodie-Cinco-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/27-MaroonZipUpHoodie-Cinco-Front.png",
          color: "Maroon",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/27-BlackZipUpHoodie-Cinco-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/27-GrayZipUpHoodie-Cinco-Front.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Maroon", "Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 23,
      title: "Cinco Ranch Lightweight Windbreaker",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 40.0,
      image: "cinco-Ranch/28-GrayZipUpHoodie-Cinco-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/28-GrayZipUpHoodie-Cinco-Front.png",
          color: "Maroon",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Maroon"],
      material: ["Windbreaker"],
      orders: [],
    },
    {
      id: 24,
      title: "Cinco Ranch Polo Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 30.0,
      image: "cinco-Ranch/29-GrayZipUpHoodie-Cinco-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/29-GrayZipUpHoodie-Cinco-Front.png",
          color: "Maroon",
        },
      ],
      sizes: sizes,
      colors: ["Maroon"],
      material: materials,
      orders: [],
    },
    {
      id: 25,
      title: "Cinco Ranch Sweatpants",
      isCustomizable: false,
      category: Categories.BOTTOMS,
      showBackSelection: false,
      isBackRequired: false,
      backOptionPrice: 2.0,
      price: 30.0,
      image: "cinco-Ranch/30-GrayJoggers-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "cinco-Ranch/30-GrayJoggers-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "cinco-Ranch/30-BlackJoggers-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "cinco-Ranch/30-BlackJoggers-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
  ],
};
