// stores/storeConfigs.ts
import { Categories } from "../../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const materials = ["Cotton", DRIFIT];
const backMock = "reign/SHIRTBACK.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const hustle = {
  id: 3,
  version: 7,
  name: "HUSTLE NATIONAL 2033",
  branding: {
    logo: "",
    primaryColor: "#ffffff",
    secondaryColor: "#00C0C0",
  },
  players: [
    { name: "Analina Ramirez", number: "2" },
    { name: "Skylar Ottele", number: "3" },
    { name: "Aaliyah Johnson", number: "8" },
    { name: "Maddi Gonzalez", number: "9" },
    { name: "Kaylee Riddle", number: "10" },
    { name: "Lilee Galvan", number: "13" },
    { name: "Sophia Ramirez", number: "19" },
    { name: "Olivia Canas", number: "17" },
    { name: "Malaya Dislate", number: "44" },
    { name: "Scarlett Torres", number: "77" },
    { name: "Coach", number: "n/a" },
  ],
  passcode: "national-closed",
  items: [
    {
      id: 1,
      title: "Hustle Jersey Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: false,
      price: 35.0,
      image:
        "hustleNational/1-BlackJerseyShirt-HustleNationalSoftball-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleNational/1-BlackJerseyShirt-HustleNationalSoftball-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl:
            "hustleNational/1-BlackJerseyShirt-HustleNationalSoftball-Back.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl:
            "hustleNational/1-NavyJerseyShirt-HustleNationalSoftball-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl:
            "hustleNational/1-NavyJerseyShirt-HustleNationalSoftball-Back.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black", "Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 2,
      title: "Born to Hustle Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/10-BlueLongSleeve-Born-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/10-BlueLongSleeve-Born-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/10-BlackLongSleeve-Born-front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 3,
      title: "Respect the Hustle Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/11-WhiteLongSleeve-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/11-WhiteLongSleeve-Respect-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleNational/11-BlackLongSleeve-Respect-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/11-BlueLongSleeve-Respect-front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/11-SilverLongSleeve-Respect-front.png",
          color: "Silver",
        },
        {
          id: 4,
          imageUrl: "hustleNational/11-GrayLongSleeve-Respect-front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Black", "Navy", "Silver", "Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 4,
      title: "Hustle Paint Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/12-GrayLongSleeve-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/12-GrayLongSleeve-Paint-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/12-BlackLongSleeve-Paint-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/12-BlueLongSleeve-Paint-front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/12-SilverLongSleeve-Paint-front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black", "Navy", "Silver"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 5,
      title: "Lined H Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/13-BlackLongSleeve-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/13-BlackLongSleeve-LinedH-front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/13-BlueLongSleeve-LinedH-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleNational/13-SilverLongSleeve-LinedH-front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Navy", "Silver"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 6,
      title: "Hustle National Block Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/14-SilverLongSleeve-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 3,
          imageUrl: "hustleNational/14-SilverLongSleeve-HustleBlock-front.png",
          color: "Silver",
        },
        {
          id: 0,
          imageUrl: "hustleNational/14-GrayLongSleeve-HustleBlock-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/14-BlackLongSleeve-HustleBlock-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/14-BlueLongSleeve-HustleBlock-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Gray", "Black", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 7,
      title: "Hustle Half Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/15-BlueLongSleeve-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 1,
          imageUrl: "hustleNational/15-BlueLongSleeve-Half-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleNational/15-WhiteLongSleeve-Half-front.png",
          color: "White",
        },
        {
          id: 0,
          imageUrl: "hustleNational/15-BlackLongSleeve-Half-front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 8,
      title: "Hustle Plate Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/16-WhiteLongSleeve-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/16-WhiteLongSleeve-HustlePlate-front.png",
          color: "White",
        },
        {
          id: 3,
          imageUrl: "hustleNational/16-SilverLongSleeve-HustlePlate-front.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleNational/16-BlackLongSleeve-HustlePlate-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/16-BlueLongSleeve-HustlePlate-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Silver", "Black", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 9,
      title: "Hustle Flag Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/9-BlackLongSleeve-Flag-front.png",
      backImage: backMock,
      images: [
        {
          id: 1,
          imageUrl: "hustleNational/9-BlackLongSleeve-Flag-front.png",
          color: "Black",
        },
        {
          id: 0,
          imageUrl: "hustleNational/9-BlueLongSleeve-Flag-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 10,
      title: "Hustle Flag Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/17-BlackHoodedLongSleeve-Flag-front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/17-BlackHoodedLongSleeve-Flag-front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 11,
      title: "Lined H Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/18-BlackHoodedLongSleeve-LinedH-front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/18-BlackHoodedLongSleeve-LinedH-front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 12,
      title: "Respect the Hustle Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/19-GrayHoodedLongSleeve-Respect-front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/19-GrayHoodedLongSleeve-Respect-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/19-BlackHoodedLongSleeve-Respect-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/19-WhiteHoodedLongSleeve-Respect-front.png",
          color: "White",
        },
      ],
      sizes: sizes,
      colors: ["Gray", "Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 13,
      title: "Hustle Paint Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/20-BlackHoodedLongSleeve-Paint-front.png",
      images: [
        {
          id: 1,
          imageUrl: "hustleNational/20-BlackHoodedLongSleeve-Paint-front.png",
          color: "Black",
        },
        {
          id: 0,
          imageUrl: "hustleNational/20-GrayHoodedLongSleeve-Paint-front.png",
          color: "Gray",
        },
      ],
      sizes: sizes,
      colors: ["Black", "Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 14,
      title: "Hustle National Block Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/21-GrayHoodedLongSleeve-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleNational/21-GrayHoodedLongSleeve-HustleBlock-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl:
            "hustleNational/21-BlackHoodedLongSleeve-HustleBlock-front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Gray", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 15,
      title: "Hustle Plate Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/22-WhiteHoodedLongSleeve-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleNational/22-WhiteHoodedLongSleeve-HustlePlate-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl:
            "hustleNational/22-BlackHoodedLongSleeve-HustlePlate-front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 16,
      title: "Hustle Half Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleNational/23-BlackHoodedLongSleeve-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/23-BlackHoodedLongSleeve-Half-front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/23-WhiteHoodedLongSleeve-Half-front.png",
          color: "White",
        },
      ],
      sizes: sizes,
      colors: ["Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 17,
      title: "Hustle H Raider Short Sleeve Quarter-Zip",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 60.0,
      image: "hustleNational/26-NavyQuarterZip-H-Front.png",
      backImage: backMock,
      images: [
        {
          id: 2,
          imageUrl: "hustleNational/26-NavyQuarterZip-H-Front.png",
          color: "Navy",
        },
        {
          id: 0,
          imageUrl: "hustleNational/26-BlackQuarterZip-H-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/26-WhiteQuarterZip-H-Front.png",
          color: "White",
        },
      ],
      sizes: sizes,
      colors: ["Navy", "Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 18,
      title: "Born to Hustle Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/32-BlackCropTop-born-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/32-BlackCropTop-born-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/32-BlackCropTop-born-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 19,
      title: "Respect the Hustle Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/30-BlackCropTop-Respect-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/30-BlackCropTop-Respect-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/30-BlackCropTop-Respect-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 20,
      title: "Hustle Paint Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/29-BlackCropTop-Paint-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/29-BlackCropTop-Paint-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/29-BlackCropTop-Paint-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 21,
      title: "Lined H Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/33-BlackCropTop-LinedH-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/33-BlackCropTop-LinedH-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/33-BlackCropTop-LinedH-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 22,
      title: "Hustle National Block Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/31-BlackCropTop-HustleBlock-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/31-BlackCropTop-HustleBlock-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/31-BlackCropTop-HustleBlock-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 23,
      title: "Hustle Half Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/34-BlackCropTop-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/34-BlackCropTop-Half-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/34-BlackCropTop-Half-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 24,
      title: "Hustle Plate Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/28-BlackCropTop-HustlePlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/28-BlackCropTop-HustlePlate-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/28-BlackCropTop-HustlePlate-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 25,
      title: "Hustle Flag Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/35-BlackCropTop-Flag-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/35-BlackCropTop-Flag-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/35-BlackCropTop-Flag-Mock.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 26,
      title: "Hustle Plate V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/36-WhiteSleevelessWomens-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleNational/36-WhiteSleevelessWomens-HustlePlate-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl:
            "hustleNational/36-BlackSleevelessWomens-HustlePlate-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 27,
      title: "Respect the Hustle V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/37-WhiteSleevelessWomens-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/37-WhiteSleevelessWomens-Respect-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleNational/37-BlackSleevelessWomens-Respect-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 28,
      title: "Hustle Half V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/38-WhiteSleevelessWomens-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/38-WhiteSleevelessWomens-Half-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleNational/38-BlackSleevelessWomens-Half-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 29,
      title: "Hustle Paint V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/39-BlackSleevelessWomens-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/39-BlackSleevelessWomens-Paint-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 30,
      title: "Hustle National Block V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/40-BlackSleevelessWomens-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleNational/40-BlackSleevelessWomens-HustleBlock-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 31,
      title: "Born to Hustle V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/41-BlackSleevelessWomens-Born-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/41-BlackSleevelessWomens-Born-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 32,
      title: "Lined H V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/42-BlackSleevelessWomens-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/42-BlackSleevelessWomens-LinedH-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 33,
      title: "Hustle Flag V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/43-BlackSleevelessWomens-Flag-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/43-BlackSleevelessWomens-Flag-front.png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 34,
      title: "Hustle Plate Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/44-GraySleeveless-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/44-GraySleeveless-HustlePlate-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/44-BlackSleeveless-HustlePlate-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/44-WhiteSleeveless-HustlePlate-front.png",
          color: "White",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 35,
      title: "Hustle Flag Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/45-BlackSleeveless-Flag-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/45-BlackSleeveless-Flag-front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/45-GraySleeveless-Flag-front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 36,
      title: "Lined H Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/46-GraySleeveless-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/46-GraySleeveless-LinedH-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/46-BlackSleeveless-LinedH-front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 37,
      title: "Born to Hustle Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/47-BlackSleeveless-Born-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/47-BlackSleeveless-Born-front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 38,
      title: "Hustle Paint Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/48-GraySleeveless-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/48-GraySleeveless-Paint-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/48-BlackSleeveless-Paint-front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 39,
      title: "Respect the Hustle Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/49-WhiteSleeveless-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/49-WhiteSleeveless-Respect-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleNational/49-BlackSleeveless-Respect-front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/49-GraySleeveless-Respect-front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Black", "Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 40,
      title: "Hustle National Block Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/50-BlackSleeveless-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/50-BlackSleeveless-HustleBlock-front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/50-GraySleeveless-HustleBlock-front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 41,
      title: "Hustle Half Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleNational/51-BlackSleeveless-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/51-BlackSleeveless-Half-front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/51-WhiteSleeveless-Half-front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl: "hustleNational/51-GraySleeveless-Half-front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "White", "Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 42,
      title: "Hustle Plate Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/52-CamoCropTopHoodie-HustlePlate-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/52-CamoCropTopHoodie-HustlePlate-Front.png",
          color: "Camo",
        },
        {
          id: 1,
          imageUrl:
            "hustleNational/52-BlackCropTopHoodie-HustlePlate-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl:
            "hustleNational/52-BlackCropTopHoodie-HustlePlate-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Camo", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 43,
      title: "Hustle Paint Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/53-BlackCropTopHoodie-Paint-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/53-BlackCropTopHoodie-Paint-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/53-CamoCropTopHoodie-Paint-Front.png",
          color: "Camo",
        },
        {
          id: 2,
          imageUrl: "hustleNational/53-BlackCropTopHoodie-Paint-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Black", "Camo"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 44,
      title: "Respect the Hustle Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/54-GrayCropTopHoodie-Respect-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/54-GrayCropTopHoodie-Respect-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/54-BlackCropTopHoodie-Respect-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/54-CamoCropTopHoodie-Respect-Front.png",
          color: "Camo",
        },
        {
          id: 3,
          imageUrl:
            "hustleNational/54-BlackCropTopHoodie-Respect-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Gray", "Black", "Camo"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 45,
      title: "Hustle National Block Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/55-CamoCropTopHoodie-HustleBlock-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/55-CamoCropTopHoodie-HustleBlock-Front.png",
          color: "Camo",
        },
        {
          id: 1,
          imageUrl:
            "hustleNational/55-BlackCropTopHoodie-HustleBlock-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/55-GrayCropTopHoodie-HustleBlock-Front.png",
          color: "Gray",
        },
        {
          id: 3,
          imageUrl:
            "hustleNational/55-BlackCropTopHoodie-HustleBlock-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Camo", "Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 46,
      title: "Born to Hustle Block Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/56-CamoCropTopHoodie-Born-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/56-CamoCropTopHoodie-Born-Front.png",
          color: "Camo",
        },
        {
          id: 1,
          imageUrl: "hustleNational/56-BlackCropTopHoodie-Born-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/56-BlackCropTopHoodie-Born-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Camo", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 47,
      title: "Lined H Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/57-GrayCropTopHoodie-LinedH-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/57-GrayCropTopHoodie-LinedH-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/57-BlackCropTopHoodie-LinedH-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/57-CamoCropTopHoodie-LinedH-Front.png",
          color: "Camo",
        },
        {
          id: 3,
          imageUrl: "hustleNational/57-BlackCropTopHoodie-LinedH-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Gray", "Black", "Camo"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 48,
      title: "Hustle Half Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/58-CamoCropTopHoodie-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/58-CamoCropTopHoodie-Half-Front.png",
          color: "Camo",
        },
        {
          id: 1,
          imageUrl: "hustleNational/58-BlackCropTopHoodie-Half-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/58-BlackCropTopHoodie-Half-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Camo", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 49,
      title: "Hustle Flag Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/59-CamoCropTopHoodie-Flag-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/59-CamoCropTopHoodie-Flag-Front.png",
          color: "Camo",
        },
        {
          id: 1,
          imageUrl: "hustleNational/59-BlackCropTopHoodie-Flag-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/59-BlackCropTopHoodie-Flag-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Camo", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 50,
      title: "Hustle Joggers",
      isCustomizable: false,
      showBackSelection: false,
      category: Categories.BOTTOMS,
      price: 35.0,
      image: "hustleNational/60-BlackJoggers-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/60-BlackJoggers-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/60-GrayJoggers-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/60-BlackJoggers-Front+(2).png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 51,
      title: "Hustle Plate Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/61-BlueShirt-HustlePlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/61-BlueShirt-HustlePlate-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/61-BlackShirt-HustlePlate-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/61-SilverShirt-HustlePlate-Front.png",
          color: "Silver",
        },
        {
          id: 3,
          imageUrl: "hustleNational/61-GrayShirt-HustlePlate-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Black", "Silver", "Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 52,
      title: "Hustle Paint Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/62-SilverShirt-Paint-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/62-SilverShirt-Paint-Front.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleNational/62-BlackShirt-Paint-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/62-BlueShirt-Paint-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/62-GrayShirt-Paint-Front.png",
          color: "Gray",
        },
        {
          id: 4,
          imageUrl: "hustleNational/62-TealShirt-Paint-Front.png",
          color: "Teal",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Black", "Navy", "Gray", "Teal"],
      material: materials,
      orders: [],
    },
    {
      id: 53,
      title: "Respect the Hustle Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/63-TealShirt-Respect-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/63-TealShirt-Respect-Front.png",
          color: "Teal",
        },
        {
          id: 1,
          imageUrl: "hustleNational/63-BlackShirt-Respect-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/63-BlueShirt-Respect-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/63-GrayShirt-Respect-Front.png",
          color: "Gray",
        },
        {
          id: 4,
          imageUrl: "hustleNational/63-SilverShirt-Respect-Front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Teal", "Black", "Navy", "Gray", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 54,
      title: "HUSTLE NATIONAL BLOCK Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/64-BlackShirt-HustleBlock-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/64-BlackShirt-HustleBlock-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/64-SilverShirt-HustleBlock-Front.png",
          color: "Silver",
        },
        {
          id: 2,
          imageUrl: "hustleNational/64-BlueShirt-HustleBlock-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/64-GrayShirt-HustleBlock-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Silver", "Navy", "Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 55,
      title: "Born to Hustle Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/65-BlueShirt-born-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/65-BlueShirt-born-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/65-GrayShirt-born-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/65-BlackShirt-born-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Gray", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 56,
      title: "Lined H Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/66-BlackShirt-LinedH-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/66-BlackShirt-LinedH-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/66-GrayShirt-LinedH-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/66-BlueShirt-LinedH-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/66-SilverShirt-LinedH-Front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray", "Navy", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 57,
      title: "Hustle Half Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/67-SilverShirt-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/67-SilverShirt-Half-Front.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleNational/67-GrayShirt-Half-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/67-BlueShirt-Half-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleNational/67-BlackShirt-Half-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Gray", "Navy", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 58,
      title: "Hustle Flag Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/68-BlueShirt-Flag-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/68-BlueShirt-Flag-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/68-BlackShirt-Flag-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 59,
      title: "Hustle Plate Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/69-GrayHoodie-HustlePlate-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/69-GrayHoodie-HustlePlate-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/69-BlackHoodie-HustlePlate-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/69-SilverHoodie-HustlePlate-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Black", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 60,
      title: "Hustle Paint Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/70-SilverHoodie-Paint-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/70-SilverHoodie-Paint-Front.png",
          color: "Light Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/70-GrayHoodie-Paint-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/70-BlackHoodie-Paint-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Light Gray", "Dark Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 61,
      title: "Respect the Hustle Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/71-BlackHoodie-Respect-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/71-BlackHoodie-Respect-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/71-GrayHoodie-Respect-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/71-SilverHoodie-Respect-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Dark Gray", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 62,
      title: "Hustle National Block Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/72-GrayHoodie-HustleBlock-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/72-GrayHoodie-HustleBlock-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/72-BlackHoodie-HustleBlock-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/72-SilverHoodie-HustleBlock-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Black", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 63,
      title: "Born to Hustle Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/73-BlackHoodie-born-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/73-BlackHoodie-born-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/73-GrayHoodie-born-Front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Dark Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 64,
      title: "Lined H Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/74-SilverHoodie-LinedH-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/74-SilverHoodie-LinedH-Front.png",
          color: "Light Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/74-BlackHoodie-LinedH-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/74-GrayHoodie-LinedH-Front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Light Gray", "Black", "Dark Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 65,
      title: "Hustle Half Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/75-BlackHoodie-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/75-BlackHoodie-Half-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/75-GrayHoodie-Half-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/75-SilverHoodie-Half-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Dark Gray", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 66,
      title: "Hustle Flag Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/76-GrayHoodie-Flag-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/76-GrayHoodie-Flag-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/76-BlackHoodie-Flag-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 67,
      title: "Hustle Customizable Shirt",
      showBackSelection: true,
      isCustomizable: true,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/77-HustleCustom-Black.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/77-HustleCustom-Black.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/77-HustleCustom-Gray.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/77-HustleCustom-Navy.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/77-HustleCustom-Teal.png",
          color: "Teal",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Dark Gray", "Navy", "Teal"],
      material: materials,
      orders: [],
    },
    {
      id: 68,
      title: "Hustle Pitcher Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/78-HustleHitter-Gray.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/78-HustleHitter-Gray.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/78-HustleHitter-Black.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "hustleNational/78-HustleHitter-Silver.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Black", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 69,
      title: "Hustle Catcher Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/79-HustleCatcher-Black.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/79-HustleCatcher-Black.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "hustleNational/79-HustleCatcher-Gray.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/79-HustleCatcher-Silver.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Dark Gray", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 70,
      title: "Hustle Hitter Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/80-HustlePitcher-Silver.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/80-HustlePitcher-Silver.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleNational/80-HustlePitcher-Gray.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/80-HustlePitcher-Black.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Dark Gray", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 71,
      title: "C'mon Blue Shirt",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/81-CmonBlue-Navy.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/81-CmonBlue-Navy.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: materials,
      orders: [],
    },
    {
      id: 72,
      title: "They see me Rollin Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/82-Rollin-Teal.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/82-Rollin-Teal.png",
          color: "Teal",
        },
        {
          id: 1,
          imageUrl: "hustleNational/82-Rollin-Navy.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleNational/82-Rollin-Black.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Teal", "Navy", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 73,
      title: "Steal I Dare You Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/83-Steal-Black.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/83-Steal-Black.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: materials,
      orders: [],
    },
    {
      id: 74,
      title: "Softball Flag Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/84-Flag-Teal.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/84-Flag-Teal.png",
          color: "Teal",
        },
        {
          id: 1,
          imageUrl: "hustleNational/84-Flag-Navy.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Teal", "Navy"],
      material: materials,
      orders: [],
    },
    {
      id: 75,
      title: "Softball Mom Life Shirt",
      showBackSelection: true,
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/85-MomLife-Navy.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/85-MomLife-Navy.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/85-MomLife-Tan.png",
          color: "Tan",
        },
        {
          id: 2,
          imageUrl: "hustleNational/85-MomLife-Teal.png",
          color: "Teal",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Tan", "Teal"],
      material: materials,
      orders: [],
    },
    {
      id: 76,
      title: "Softball Mom Life Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/86-MomLifeHoodie-Navy.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/86-MomLifeHoodie-Navy.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/86-MomLifeHoodie-Tan.png",
          color: "Tan",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Tan"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 77,
      title: "Softball Flag Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleNational/87-FlagHoodie-Navy.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/87-FlagHoodie-Navy.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/87-FlagHoodie-Gray.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/87-FlagHoodie-Army.png",
          color: "Army",
        },
        {
          id: 3,
          imageUrl: "hustleNational/87-FlagHoodie-Tan.png",
          color: "Tan",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Gray", "Army", "Tan"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 78,
      title: "Hustle Come & Get It Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/82-HustleCome&getit-Gray.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/82-HustleCome&getit-Gray.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleNational/82-HustleCome&getit-Navy.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleNational/82-HustleCome&getit-Black.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Navy", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 79,
      title: "Hustle National Come & Get It Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleNational/81-HustleNationalCome&getit-Navy.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleNational/81-HustleNationalCome&getit-Navy.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleNational/81-HustleNationalCome&getit-Gray.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleNational/81-HustleNationalCome&getit-Black.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Gray", "Black"],
      material: materials,
      orders: [],
    },
  ],
};

// Add more stores as needed...
