// stores/storeConfigs.ts
import { Categories } from "../../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const materials = ["Cotton", DRIFIT];
const backMock = "reign/SHIRTBACK.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const hustlelctx = {
  id: 6,
  version: 1,
  name: "HUSTLE LCTX 2K14",
  branding: {
    logo: "",
    primaryColor: "#ffffff",
    secondaryColor: "#00C0C0",
  },
  players: [
    { name: "Krisella Salas", number: "2" },
    { name: "Ellie Wilson", number: "6" },
    { name: "Sabrina Mottu", number: "7" },
    { name: "Kinley Snyder", number: "8" },
    { name: "Sophia Mottu", number: "9" },
    { name: "Avery Turner", number: "21" },
    { name: "Rose McKinnon", number: "27" },
    { name: "Madelyn Mejia", number: "33" },
    { name: "Skar De La Cruz", number: "55" },
    { name: "Coach", number: "n/a" },
  ],
  passcode: "hustlelctx",
  items: [
    {
      id: 1,
      title: "Hustle Jersey Shirt",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: false,
      price: 35.0,
      image:
        "hustleLCTX2k14/1-NavyJerseyShirt-HustleNationalSoftball-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/1-NavyJerseyShirt-HustleNationalSoftball-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl:
            "hustleLCTX2k14/1-NavyJerseyShirt-HustleNationalSoftball-Back.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL"],
      colors: ["Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 2,
      title: "Born to Hustle Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/3-NavyLongSleeve-Born-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/3-NavyLongSleeve-Born-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 3,
      title: "Respect the Hustle Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/4-WhiteLongSleeve-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/4-WhiteLongSleeve-Respect-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/4-NavyLongSleeve-Respect-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/4-SilverLongSleeve-Respect-front.png",
          color: "Silver",
        },
        {
          id: 3,
          imageUrl: "hustleLCTX2k14/4-DarkGrayLongSleeve-Respect-front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Navy", "Silver", "Dark Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 4,
      title: "Hustle Paint Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/5-DarkGrayLongSleeve-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/5-DarkGrayLongSleeve-Paint-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/5-NavyLongSleeve-Paint-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 5,
      title: "Lined H Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/6-NavyLongSleeve-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/6-NavyLongSleeve-LinedH-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/6-SilverLongSleeve-LinedH-front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Silver"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 6,
      title: "Hustle Softball Block Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/7-SilverLongSleeve-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/7-SilverLongSleeve-HustleBlock-front.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/7-DarkGrayLongSleeve-HustleBlock-front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/7-NavyLongSleeve-HustleBlock-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Dark Gray", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 7,
      title: "Hustle Half Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/8-NavyLongSleeve-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/8-NavyLongSleeve-Half-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/8-WhiteLongSleeve-Half-front.png",
          color: "White",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 8,
      title: "Hustle Plate Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/9-WhiteLongSleeve-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/9-WhiteLongSleeve-HustlePlate-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/9-SilverLongSleeve-HustlePlate-front.png",
          color: "Silver",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/9-NavyLongSleeve-HustlePlate-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Silver", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 9,
      title: "Hustle Flag Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/2-NavyLongSleeve-Flag-front.png",
      backImage: backMock,
      images: [
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/2-NavyLongSleeve-Flag-front.png",
          color: "Navy",
        },
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/2-DarkGrayLongSleeve-Flag-front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Dark Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 10,
      title: "Hustle Flag Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/10-NavyHoodedLongSleeve-HustleFlag-front.png",
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/10-NavyHoodedLongSleeve-HustleFlag-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 11,
      title: "Lined H Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/14-NavyHoodedLongSleeve-LinedH-front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/14-NavyHoodedLongSleeve-LinedH-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 12,
      title: "Respect the Hustle Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/12-DarkGrayHoodedLongSleeve-Respect-front.png",
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/12-DarkGrayHoodedLongSleeve-Respect-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/12-NavyHoodedLongSleeve-Respect-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Dark Gray", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 13,
      title: "Hustle Paint Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/13-DarkGrayHoodedLongSleeve-Paint-front.png",
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/13-DarkGrayHoodedLongSleeve-Paint-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/13-NavyHoodedLongSleeve-Paint-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Black", "Dark Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 14,
      title: "Hustle Softball Block Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/15-NavyHoodedLongSleeve-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/15-NavyHoodedLongSleeve-HustleBlock-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl:
            "hustleLCTX2k14/15-DarkGrayHoodedLongSleeve-HustleBlock-front.png",
          color: "Dark Gray",
        },
      ],
      sizes: sizes,
      colors: ["Navy", "Dark Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 15,
      title: "Hustle Plate Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/17-NavyHoodedLongSleeve-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/17-NavyHoodedLongSleeve-HustlePlate-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 16,
      title: "Hustle Half Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/16-NavyHoodedLongSleeve-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/16-NavyHoodedLongSleeve-Half-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 67,
      title: "Born to Hustle Long Sleeve with Hood",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      price: 25.0,
      image: "hustleLCTX2k14/11-NavyHoodedLongSleeve-HustleBorn-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/11-NavyHoodedLongSleeve-HustleBorn-front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 17,
      title: "Hustle H Raider Short Sleeve Quarter-Zip",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 60.0,
      image: "hustleLCTX2k14/18-WhiteQuarterZip-H-Front.png",
      backImage: backMock,
      images: [
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/18-WhiteQuarterZip-H-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/18-NavyQuarterZip-H-Front.png",
          color: "Navy",
        },
      ],
      sizes: sizes,
      colors: ["White", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 18,
      title: "Born to Hustle Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/20-NavyCropTopShirt-HustleBorn-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/20-NavyCropTopShirt-HustleBorn-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/20-NavyCropTopShirt-HustleBorn-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 19,
      title: "Respect the Hustle Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/21-GrayCropTopShirt-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/21-GrayCropTopShirt-Respect-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/21-NavyCropTopShirt-Respect-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/21-NavyCropTopShirt-Respect-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Gray", "Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 20,
      title: "Hustle Paint Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/22-NavyCropTopShirt-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/22-NavyCropTopShirt-Paint-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/22-NavyCropTopShirt-Paint-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 21,
      title: "Lined H Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/23-GrayCropTopShirt-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/23-GrayCropTopShirt-LinedH-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/23-NavyCropTopShirt-LinedH-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/23-NavyCropTopShirt-LinedH-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Gray", "Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 22,
      title: "Hustle Softball Block Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/24-NavyCropTopShirt-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/24-NavyCropTopShirt-HustleBlock-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/24-GrayCropTopShirt-HustleBlock-front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/24-NavyCropTopShirt-HustleBlock-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Navy", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 23,
      title: "Hustle Half Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/25-NavyCropTopShirt-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/25-NavyCropTopShirt-Half-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/25-NavyCropTopShirt-Half-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 24,
      title: "Hustle Plate Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/26-GrayCropTopShirt-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/26-GrayCropTopShirt-HustlePlate-front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/26-NavyCropTopShirt-HustlePlate-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/26-NavyCropTopShirt-HustlePlate-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Gray", "Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 25,
      title: "Hustle Flag Crop Top",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/19-NavyCropTopShirt-HustleFlag-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/19-NavyCropTopShirt-HustleFlag-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/19-SilverCropTopShirt-HustleFlag-front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/19-NavyCropTopShirt-HustleFlag-Mock.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Navy", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 26,
      title: "Hustle Plate V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/34-NavySleevelessWomens-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/34-NavySleevelessWomens-HustlePlate-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl:
            "hustleLCTX2k14/34-WhiteSleevelessWomens-HustlePlate-front.png",
          color: "White",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 27,
      title: "Respect the Hustle V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/29-WhiteSleevelessWomens-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/29-WhiteSleevelessWomens-Respect-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/29-NavySleevelessWomens-Respect-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["White", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 28,
      title: "Hustle Half V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/33-NavySleevelessWomens-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/33-NavySleevelessWomens-Half-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 29,
      title: "Hustle Paint V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/30-NavySleevelessWomens-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/30-NavySleevelessWomens-Paint-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 30,
      title: "Hustle Softball Block V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/32-NavySleevelessWomens-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/32-NavySleevelessWomens-HustleBlock-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 31,
      title: "Born to Hustle V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/28-NavySleevelessWomens-Born-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/28-NavySleevelessWomens-Born-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 32,
      title: "Lined H V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/31-NavySleevelessWomens-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/31-NavySleevelessWomens-LinedH-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 33,
      title: "Hustle Flag V-Neck Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/27-NavySleevelessWomens-HustleFlag-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/27-NavySleevelessWomens-HustleFlag-front.png",
          color: "Navy",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 34,
      title: "Hustle Plate Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/42-WhiteSleeveless-HustlePlate-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/42-WhiteSleeveless-HustlePlate-front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/42-NavySleeveless-HustlePlate-front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl:
            "hustleLCTX2k14/42-DarkGraySleeveless-HustlePlate-front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Navy", "Dark Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 35,
      title: "Hustle Flag Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/35-NavySleeveless-HustleFlag-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/35-NavySleeveless-HustleFlag-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 36,
      title: "Lined H Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/39-DarkGraySleeveless-LinedH-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/39-DarkGraySleeveless-LinedH-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/39-NavySleeveless-LinedH-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 37,
      title: "Born to Hustle Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/36-NavySleeveless-Born-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/36-NavySleeveless-Born-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 38,
      title: "Hustle Paint Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/38-DarkGraySleeveless-Paint-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/38-DarkGraySleeveless-Paint-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/38-NavySleeveless-Paint-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 39,
      title: "Respect the Hustle Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/37-NavySleeveless-Respect-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/37-NavySleeveless-Respect-front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/37-DarkGraySleeveless-Respect-front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Dark Gray"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 40,
      title: "Hustle Softball Block Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/40-DarkGraySleeveless-HustleBlock-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "hustleLCTX2k14/40-DarkGraySleeveless-HustleBlock-front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/40-NavySleeveless-HustleBlock-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 41,
      title: "Hustle Half Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 20.0,
      image: "hustleLCTX2k14/41-NavySleeveless-Half-front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/41-NavySleeveless-Half-front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 42,
      title: "Hustle Plate Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/48-GrayCropTopHoodie-Plate-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/48-GrayCropTopHoodie-Plate-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/48-GrayCropTopHoodie-Plate-Mock.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    // {
    //   id: 43,
    //   title: "Hustle Paint Crop Top Hoodie",
    //   showBackSelection: false,
    //   isCustomizable: false,
    //   category: Categories.HOODIES,
    //   price: 35.0,
    //   image: "hustleNational/53-BlackCropTopHoodie-Paint-Front.png",
    //   images: [
    //     {
    //       id: 0,
    //       imageUrl: "hustleNational/53-BlackCropTopHoodie-Paint-Front.png",
    //       color: "Black",
    //     },
    //     {
    //       id: 1,
    //       imageUrl: "hustleNational/53-CamoCropTopHoodie-Paint-Front.png",
    //       color: "Camo",
    //     },
    //     {
    //       id: 2,
    //       imageUrl: "hustleNational/53-BlackCropTopHoodie-Paint-Front+(2).png",
    //       color: "Black",
    //     },
    //   ],
    //   sizes: ["S", "M", "L", "XL", "2XL"],
    //   colors: ["Black", "Camo"],
    //   material: ["Cotton"],
    //   orders: [],
    // },
    {
      id: 44,
      title: "Respect the Hustle Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/44-GrayCropTopHoodie-Respect-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/44-GrayCropTopHoodie-Respect-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/44-GrayCropTopHoodie-Respect-Mock.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 45,
      title: "Hustle Softball Block Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/46-GrayCropTopHoodie-Block-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/46-GrayCropTopHoodie-Block-Front.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    // {
    //   id: 46,
    //   title: "Born to Hustle Crop Top Hoodie",
    //   showBackSelection: false,
    //   isCustomizable: false,
    //   category: Categories.HOODIES,
    //   price: 35.0,
    //   image: "hustleNational/56-CamoCropTopHoodie-Born-Front.png",
    //   backImage: backMock,
    //   images: [
    //     {
    //       id: 0,
    //       imageUrl: "hustleNational/56-CamoCropTopHoodie-Born-Front.png",
    //       color: "Camo",
    //     },
    //     {
    //       id: 1,
    //       imageUrl: "hustleNational/56-BlackCropTopHoodie-Born-Front.png",
    //       color: "Black",
    //     },
    //     {
    //       id: 2,
    //       imageUrl: "hustleNational/56-BlackCropTopHoodie-Born-Front+(2).png",
    //       color: "Black",
    //     },
    //   ],
    //   sizes: ["S", "M", "L", "XL", "2XL"],
    //   colors: ["Camo", "Black"],
    //   material: ["Cotton"],
    //   orders: [],
    // },
    // {
    //   id: 47,
    //   title: "Lined H Crop Top Hoodie",
    //   showBackSelection: false,
    //   isCustomizable: false,
    //   category: Categories.HOODIES,
    //   price: 35.0,
    //   image: "hustleNational/57-GrayCropTopHoodie-LinedH-Front.png",
    //   backImage: backMock,
    //   images: [
    //     {
    //       id: 0,
    //       imageUrl: "hustleNational/57-GrayCropTopHoodie-LinedH-Front.png",
    //       color: "Gray",
    //     },
    //     {
    //       id: 1,
    //       imageUrl: "hustleNational/57-BlackCropTopHoodie-LinedH-Front.png",
    //       color: "Black",
    //     },
    //     {
    //       id: 2,
    //       imageUrl: "hustleNational/57-CamoCropTopHoodie-LinedH-Front.png",
    //       color: "Camo",
    //     },
    //     {
    //       id: 3,
    //       imageUrl: "hustleNational/57-BlackCropTopHoodie-LinedH-Front+(2).png",
    //       color: "Black",
    //     },
    //   ],
    //   sizes: ["S", "M", "L", "XL", "2XL"],
    //   colors: ["Gray", "Black", "Camo"],
    //   material: ["Cotton"],
    //   orders: [],
    // },
    {
      id: 48,
      title: "Hustle Half Crop Top Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/47-GrayCropTopHoodie-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/47-GrayCropTopHoodie-Half-Front.png",
          color: "Gray",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    // {
    //   id: 49,
    //   title: "Hustle Flag Crop Top Hoodie",
    //   showBackSelection: false,
    //   isCustomizable: false,
    //   category: Categories.HOODIES,
    //   price: 35.0,
    //   image: "hustleNational/59-CamoCropTopHoodie-Flag-Front.png",
    //   backImage: backMock,
    //   images: [
    //     {
    //       id: 0,
    //       imageUrl: "hustleNational/59-CamoCropTopHoodie-Flag-Front.png",
    //       color: "Camo",
    //     },
    //     {
    //       id: 1,
    //       imageUrl: "hustleNational/59-BlackCropTopHoodie-Flag-Front.png",
    //       color: "Black",
    //     },
    //     {
    //       id: 2,
    //       imageUrl: "hustleNational/59-BlackCropTopHoodie-Flag-Front+(2).png",
    //       color: "Black",
    //     },
    //   ],
    //   sizes: ["S", "M", "L", "XL", "2XL"],
    //   colors: ["Camo", "Black"],
    //   material: ["Cotton"],
    //   orders: [],
    // },
    {
      id: 50,
      title: "Hustle Joggers",
      isCustomizable: false,
      showBackSelection: false,
      category: Categories.BOTTOMS,
      price: 35.0,
      image: "hustleLCTX2k14/49-GrayJoggers-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/49-GrayJoggers-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 51,
      title: "Hustle Plate Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/57-SilverShirt-HustlePlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/57-SilverShirt-HustlePlate-Front.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/57-NavyShirt-HustlePlate-Front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Navy"],
      material: materials,
      orders: [],
    },
    {
      id: 52,
      title: "Hustle Paint Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/53-TealShirt-Paint-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/53-TealShirt-Paint-Front.png",
          color: "Teal",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/53-DarkGrayShirt-Paint-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/53-NavyShirt-Paint-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleLCTX2k14/53-SilverShirt-Paint-Front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Teal", "Dark Gray", "Navy", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 53,
      title: "Respect the Hustle Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/52-DarkGrayShirt-Respect-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/52-DarkGrayShirt-Respect-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/52-TealShirt-Respect-Front.png",
          color: "Teal",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/52-NavyShirt-Respect-Front.png",
          color: "Navy",
        },
        {
          id: 3,
          imageUrl: "hustleLCTX2k14/52-SilverShirt-Respect-Front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Teal", "Navy", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 54,
      title: "Hustle Softball Block Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/55-NavyShirt-HustleBlock-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/55-NavyShirt-HustleBlock-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/55-SilverShirt-HustleBlock-Front.png",
          color: "Silver",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/55-DarkGrayShirt-HustleBlock-Front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Silver", "Dark Gray"],
      material: materials,
      orders: [],
    },
    {
      id: 55,
      title: "Born to Hustle Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/51-NavyShirt-Born-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/51-NavyShirt-Born-Front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: materials,
      orders: [],
    },
    {
      id: 56,
      title: "Lined H Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/54-SilverShirt-LinedH-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/54-SilverShirt-LinedH-Front.png",
          color: "Silver",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/54-DarkGrayShirt-LinedH-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/54-NavyShirt-LinedH-Front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Silver", "Dark Gray", "Navy"],
      material: materials,
      orders: [],
    },
    {
      id: 57,
      title: "Hustle Half Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/56-NavyShirt-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/56-NavyShirt-Half-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/56-SilverShirt-Half-Front.png",
          color: "Silver",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Silver"],
      material: materials,
      orders: [],
    },
    {
      id: 58,
      title: "Hustle Flag Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      price: 25.0,
      image: "hustleLCTX2k14/50-DarkGrayShirt-HustleFlag-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/50-DarkGrayShirt-HustleFlag-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/50-NavyShirt-HustleFlag-Front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy"],
      material: materials,
      orders: [],
    },
    {
      id: 59,
      title: "Hustle Plate Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/65-DarkGrayHoodie-HustlePlate-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/65-DarkGrayHoodie-HustlePlate-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/65-NavyHoodie-HustlePlate-Front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/65-GrayHoodie-HustlePlate-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 60,
      title: "Hustle Paint Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/61-GrayHoodie-Paint-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/61-GrayHoodie-Paint-Front.png",
          color: "Light Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/61-DarkGrayHoodie-Paint-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/61-NavyHoodie-Paint-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Light Gray", "Dark Gray", "Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 61,
      title: "Respect the Hustle Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/60-NavyHoodie-Respect-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/60-NavyHoodie-Respect-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/60-DarkGrayHoodie-Respect-Front.png",
          color: "Dark Gray",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/60-GrayHoodie-Respect-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Dark Gray", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 62,
      title: "Hustle Softball Block Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/63-GrayHoodie-HustleBlock-Front.png",
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/63-GrayHoodie-HustleBlock-Front.png",
          color: "Light Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/63-NavyHoodie-HustleBlock-Front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/63-DarkGrayHoodie-HustleBlock-Front.png",
          color: "Dark Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Light Gray", "Navy", "Dark Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 63,
      title: "Born to Hustle Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/59-NavyHoodie-HustleBorn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/59-NavyHoodie-HustleBorn-Front.png",
          color: "Navy",
        },
      ],
      sizes: allSizes,
      colors: ["Navy"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 64,
      title: "Lined H Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/62-DarkGrayHoodie-LinedH-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/62-DarkGrayHoodie-LinedH-Front.png",
          color: "Dark Gray",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/62-NavyHoodie-LinedH-Front.png",
          color: "Navy",
        },
        {
          id: 2,
          imageUrl: "hustleLCTX2k14/62-GrayHoodie-LinedH-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Dark Gray", "Navy", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 65,
      title: "Hustle Half Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/64-NavyHoodie-Half-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/64-NavyHoodie-Half-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/64-GrayHoodie-Half-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 66,
      title: "Hustle Flag Hoodie",
      showBackSelection: false,
      isCustomizable: false,
      category: Categories.HOODIES,
      price: 35.0,
      image: "hustleLCTX2k14/58-NavyHoodie-HustleFlag-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "hustleLCTX2k14/58-NavyHoodie-HustleFlag-Front.png",
          color: "Navy",
        },
        {
          id: 1,
          imageUrl: "hustleLCTX2k14/58-GrayHoodie-HustleFlag-Front.png",
          color: "Light Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Navy", "Light Gray"],
      material: ["Cotton"],
      orders: [],
    },
  ],
};

// Add more stores as needed...
