import { Categories } from "../../../_types";
export const DRIFIT = "Dri-Fit (+ $5)";
const youthSizes = ["YS", "YM", "YL", "YXL"];
const sizes = ["S", "M", "L", "XL", "2XL", "3XL", "4XL"];
const allSizes = [...youthSizes, ...sizes];
const materials = ["Cotton", DRIFIT];
const backMock = "reign/SHIRTBACK.png";
export const DEFAULT_PLAYER_NUMBER = "n/a";
export const coach = { name: "Coach", number: DEFAULT_PLAYER_NUMBER };
export const reign = {
  id: 5,
  version: 6,
  name: "REIGN",
  branding: {
    logo: "",
    primaryColor: "#ffffff",
    secondaryColor: "#00C0C0",
  },
  players: [
    { name: "Aria Etuk", number: "17" },
    { name: "Mya Bhutani", number: "12" },
    { name: "Charlotte Bean", number: "10" },
    { name: "Ainsley Elledge", number: "1" },
    { name: "Madeline Garcia", number: "9" },
    { name: "Raelynn Correll", number: "13" },
    { name: "Kaia Sherman", number: "5" },
    { name: "Shanvi Patil", number: "77" },
    { name: "Brinley Kanzleiter", number: "8" },
    { name: "Grayson Hayes", number: "19" },
    { name: "Arya Bhutani", number: "18" },
    { name: "Londyn Lewis", number: "2" },
    { name: "Penelope Levron", number: "99" },
    { name: "Sophia Levron", number: "34" },
    { name: "Arinna Li", number: "0" },
    { name: "Eleanor Ridley", number: "7" },
    { name: "Lucille Ridley", number: "6" },
    { name: "Olivia Sillers", number: "88" },
    { name: "Tensley Wheeler", number: "00" },
    { name: "Stella White", number: "3" },
    { name: "Nora Yousef", number: "23" },
    { name: "Sofia Zapata", number: "11" },
    { name: "Camila Avilez", number: "21" },
    { name: "Isabelle Armijo", number: "22" },
    { name: "Lauren Schaefer", number: "4" },
    { name: "Aubrey Castro", number: "28" },
    { name: "Morgan Spring", number: "33" },
    { name: "Coach", number: "n/a" },
  ],
  passcode: "reign",
  items: [
    {
      id: 1,
      title: "Reign Jersey",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 15.0,
      image: "reign/2-Purple-Jersey-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/2-Purple-Jersey-Front.png",
          color: "Purple",
        },
        {
          id: 2,
          imageUrl: "reign/1-White-Jersey-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/2-Black-Jersey-Front+(1).png",
          color: "Black",
        },
        {
          id: 3,
          imageUrl: "reign/2-Purple-Jersey-FrontAndBack.png",
          color: "White",
        },
      ],
      sizes: allSizes,
      colors: ["Purple", "White", "Black"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 2,
      title: "Reign Practice Shorts",
      isCustomizable: false,
      category: Categories.BOTTOMS,
      showBackSelection: false,
      price: 15.0,
      image: "reign/3-Purple-PracticeShorts-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/3-Purple-PracticeShorts-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/3-Black-PracticeShorts-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/3-Purple-PracticeShorts-LOGO.png",
          color: "Purple",
        },
      ],
      sizes: ["YXS", "YS", "YM", "YL", "YXL", "S", "M", "L", "XL", "2XL"],
      colors: ["Purple", "Black"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 3,
      title: "Reign Womens Shorts",
      isCustomizable: false,
      category: Categories.BOTTOMS,
      showBackSelection: false,
      price: 25.0,
      image: "reign/4-Purple-WomensShorts-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/4-Purple-WomensShorts-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/4-Purple-WomensShorts-Side.png",
          color: "Purple",
        },
        {
          id: 2,
          imageUrl: "reign/4-Purple-WomensShorts-LOGO.png",
          color: "Purple",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL"],
      colors: ["Purple"],
      material: ["Dri-Fit"],
      orders: [],
    },
    {
      id: 4,
      title: "Reign Mens 7in. Inseam Shorts",
      isCustomizable: false,
      category: Categories.BOTTOMS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/5-Purple-MensShorts-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/5-Purple-MensShorts-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/5-Black-MensShorts-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/5-Purple-MensShorts-LOGO.png",
          color: "Purple",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
      colors: ["Purple", "Black"],
      material: ["Mesh"],
      orders: [],
    },
    {
      id: 5,
      title: "Reign Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/6-Black-Hoodie-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/6-Black-Hoodie-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/6-Purple-Hoodie-Front.png",
          color: "Purple",
        },
        {
          id: 2,
          imageUrl: "reign/6-Gray-Hoodie-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Purple", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 6,
      title: "Reign Joggers",
      isCustomizable: false,
      category: Categories.BOTTOMS,
      showBackSelection: false,
      price: 25.0,
      image: "reign/7-Black-Joggers-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/7-Black-Joggers-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/7-Black-Joggers-Mockup.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 7,
      title: "Reign Long Sleeve",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/8-White-LongSleeve-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/8-White-LongSleeve-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/8-Black-LongSleeve-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/8-Purple-LongSleeve-Front.png",
          color: "Purple",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Black", "Purple"],
      material: materials,
      orders: [],
    },
    {
      id: 8,
      title: "Reign Quarter Zip Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 60.0,
      image: "reign/9-White-QuarterZipMens-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/9-White-QuarterZipMens-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/9-Black-QuarterZipMens-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/9-Purple-QuarterZipMens-Front.png",
          color: "Purple",
        },
        {
          id: 3,
          imageUrl: "reign/9-Purple-QuarterZipMens-Side.png",
          color: "Purple",
        },
        {
          id: 4,
          imageUrl: "reign/9-Purple-QuarterZipMens-Back.png",
          color: "Purple",
        },
        {
          id: 5,
          imageUrl: "reign/9-QuarterZipMens-LOGO.png",
          color: "White",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["White", "Black", "Purple"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 9,
      title: "Reign Mens Polo Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/10-Purple-MensPolo-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/10-Purple-MensPolo-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/10-Black-MensPolo-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/10-White-MensPolo-Front.png",
          color: "White",
        },
        {
          id: 3,
          imageUrl: "reign/9-QuarterZipMens-LOGO.png",
          color: "White",
        },
      ],
      sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
      colors: ["Purple", "Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 10,
      title: "Long May She Reign Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/41-BlackHoodie-LongReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/41-BlackHoodie-LongReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/41-GrayHoodie-LongReign-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 11,
      title: "Long May She Reign Crop Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/41-GrayCropHoodie-LongReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/41-GrayCropHoodie-LongReign-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "reign/41-BlackCropHoodie-LongReign-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/41-BlackCropHoodie-LongReign-Mockup.png",
          color: "Mock",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 12,
      title: "Long May She Reign Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/40-BlackLongSleeve-LongReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/40-BlackLongSleeve-LongReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/40-WhiteLongSleeve-LongReign-Front.png",
          color: "White",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "White"],
      material: materials,
      orders: [],
    },
    {
      id: 13,
      title: "Long May She Reign Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/38-GrayShirt-LongReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/38-GrayShirt-LongReign-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "reign/38-BlackShirt-LongReign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 14,
      title: "Long May She Reign with Plate Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/37-BlackHoodie-ReignPlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/37-BlackHoodie-ReignPlate-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/37-GrayHoodie-ReignPlate-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 15,
      title: "Long May She Reign with Plate Crop Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/37-GrayCropHoodie-ReignPlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/37-GrayCropHoodie-ReignPlate-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "reign/37-BlackCropHoodie-ReignPlate-Front.png",
          color: "Black",
        },
        {
          id: 2,
          imageUrl: "reign/37-BlackCropHoodie-ReignPlate-Mockup.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 16,
      title: "Long May She Reign with Plate Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/36-WhiteLongSleeve-ReignPlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/36-WhiteLongSleeve-ReignPlate-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/36-PurpleLongSleeve-ReignPlate-Front.png",
          color: "Purple",
        },
        {
          id: 2,
          imageUrl: "reign/36-BlackLongSleeve-ReignPlate-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Purple", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 17,
      title: "Long May She Reign with Plate Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/34-PurpleShirt-ReignPlate-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/34-PurpleShirt-ReignPlate-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/34-GrayShirt-ReignPlate-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "reign/34-BlackShirt-ReignPlate-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Purple", "Gray", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 18,
      title: "Custom Reign Crown Hoodie",
      isCustomizable: true,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/33-GrayHoodie-CustomCrown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/33-GrayHoodie-CustomCrown-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "reign/33-BlackHoodie-CustomCrown-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 19,
      title: "Custom Reign Crown Long Sleeve",
      isCustomizable: true,
      category: Categories.LONG_SLEEVE,
      showBackSelection: false,
      price: 25.0,
      image: "reign/32-PurpleLongSleeveShirt-CustomCrown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/32-PurpleLongSleeveShirt-CustomCrown-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/32-WhiteLongSleeveShirt-CustomCrown-Front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl: "reign/32-BlackLongSleeveShirt-CustomCrown-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Purple", "White", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 20,
      title: "Custom Reign Crown Shirt",
      isCustomizable: true,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/30-BlackShirt-CustomCrown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/30-BlackShirt-CustomCrown-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/30-GrayShirt-CustomCrown-Front.png",
          color: "Gray",
        },
        {
          id: 2,
          imageUrl: "reign/30-PurpleShirt-CustomCrown-Front.png",
          color: "Purple",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray", "Purple"],
      material: materials,
      orders: [],
    },
    {
      id: 21,
      title: "Reign On Crop Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/29-BlackCropTopHoodie-ReignOn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/29-BlackCropTopHoodie-ReignOn-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/29-BlackCropTopHoodie-ReignOn-Mockup.png",
          color: "Mockup",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 22,
      title: "Reign On Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/28-BlackLongSleeve-ReignOn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/28-BlackLongSleeve-ReignOn-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: materials,
      orders: [],
    },
    {
      id: 23,
      title: "Reign On Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/27-GrayShirt-ReignOn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/27-GrayShirt-ReignOn-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "reign/27-BlackShirt-ReignOn-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 24,
      title: "Fancy Reign Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/26-BlackHoodie-FancyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/26-BlackHoodie-FancyReign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 25,
      title: "Fancy Reign Crop Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/26-BlackCropHoodie-FancyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/26-BlackCropHoodie-FancyReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/26-BlackCropHoodie-FancyReign-Model.png",
          color: "Mockup",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 26,
      title: "Fancy Reign Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/25-BlackLongSleeve-FancyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/25-BlackLongSleeve-FancyReign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: materials,
      orders: [],
    },
    {
      id: 27,
      title: "Fancy Reign Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/23-BlackShirt-FancyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/23-BlackShirt-FancyReign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: materials,
      orders: [],
    },
    {
      id: 28,
      title: "Reign Mom Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/22mom-PurpleHoodie-CustomReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/22mom-PurpleHoodie-CustomReign-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/22mom-BlackHoodie-MomCustomReign-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Purple", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 29,
      title: "Reign Dad Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/22dad-BlackHoodie-DadCustomReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/22dad-BlackHoodie-DadCustomReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/22dad-PurpleHoodie-DadCustomReign-Front.png",
          color: "Purple",
        },
      ],
      sizes: sizes,
      colors: ["Purple", "Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 30,
      title: "Reign Dad Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/21dad-PurpleLongSleeveShirt-CustomReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/21dad-PurpleLongSleeveShirt-CustomReign-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/21dad-BlackLongSleeveShirt-CustomReign-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Purple", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 42,
      title: "Reign Mom Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/21mom-BlackLongSleeveShirt-CustomReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/21mom-BlackLongSleeveShirt-CustomReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/21mom-PurpleLongSleeveShirt-CustomReign-Front.png",
          color: "Purple",
        },
      ],
      sizes: sizes,
      colors: ["Purple", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 31,
      title: "Reign Mom Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/20mom-PurpleShirt-CustomReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/20mom-PurpleShirt-CustomReign-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/20mom-BlackShirt-CustomReign-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Black", "Purple"],
      material: materials,
      orders: [],
    },
    {
      id: 32,
      title: "Reign Dad Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/20dad-BlackShirt-CustomReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/20dad-BlackShirt-CustomReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/20dad-PurpleShirt-CustomReign-Front.png",
          color: "Purple",
        },
      ],
      sizes: sizes,
      colors: ["Black", "Purple"],
      material: materials,
      orders: [],
    },
    {
      id: 33,
      title: "Purple Reign Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/18-BlackHoodie-KatyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/18-BlackHoodie-KatyReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/18-GrayHoodie-KatyReign-Front.png",
          color: "Gray",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "Gray"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 34,
      title: "Purple Reign Crop Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/18-BlackCropHoodie-KatyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/18-BlackCropHoodie-KatyReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/18-BlackCropHoodie-KatyReign-Model.png",
          color: "Mockup",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 35,
      title: "Purple Reign Long Sleeve Quarter Zip",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: false,
      price: 25.0,
      image: "reign/19-WhiteQuarterZipperLongSleeve-KatyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/19-WhiteQuarterZipperLongSleeve-KatyReign-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/19-BlackQuarterZipperLongSleeve-KatyReign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 36,
      title: "Purple Reign Long Sleeve",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: true,
      price: 25.0,
      image: "reign/17-BlackLongSleeve-KatyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/17-BlackLongSleeve-KatyReign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/17-WhiteLongSleeve-KatyReign-Front.png",
          color: "White",
        },
      ],
      sizes: allSizes,
      colors: ["White", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 37,
      title: "Purple Reign Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: true,
      price: 20.0,
      image: "reign/15-GrayShirt-KatyReign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/15-GrayShirt-KatyReign-Front.png",
          color: "Gray",
        },
        {
          id: 1,
          imageUrl: "reign/15-BlackShirt-KatyReign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Gray", "Black"],
      material: materials,
      orders: [],
    },
    {
      id: 38,
      title: "Reign Full Zip Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/14-BlackFullZipHoodie-Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/14-BlackFullZipHoodie-Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: allSizes,
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 39,
      title: "Reign Quarter Zip Windbreaker Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/13-BlackRainHoodie-Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/13-BlackRainHoodie-Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Black"],
      material: ["Windbreaker"],
      orders: [],
    },
    {
      id: 40,
      title: "Reign Quarter Zip Windbreaker Crop Hoodie",
      isCustomizable: false,
      category: Categories.HOODIES,
      showBackSelection: false,
      price: 35.0,
      image: "reign/12-WhiteCropRainHoodie-Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/12-WhiteCropRainHoodie-Reign-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/12-BlackCropRainHoodie-Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["White", "Black"],
      material: ["Windbreaker"],
      orders: [],
    },
    {
      id: 41,
      title: "Reign Long Sleeve Quarter Zip",
      isCustomizable: false,
      category: Categories.LONG_SLEEVE,
      showBackSelection: false,
      price: 25.0,
      image: "reign/11-+BlackQuarterZipperLongSleeve-Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/11-+BlackQuarterZipperLongSleeve-Reign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/11-WhiteQuarterZipperLongSleeve-Reign-Front.png",
          color: "White",
        },
      ],
      sizes: allSizes,
      colors: ["Black", "White"],
      material: materials,
      orders: [],
    },
    {
      id: 43,
      title: "Reign Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/109-Purple+Sleeveless-JerseyLogo-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/109-Purple+Sleeveless-JerseyLogo-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/109-White+Sleeveless-JerseyLogo-Front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl: "reign/109-Black+Sleeveless-JerseyLogo-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Purple", "White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 44,
      title: "Reign Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/110-White+Sleeveless-JerseyLogo-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/110-White+Sleeveless-JerseyLogo-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/110-Black+Sleeveless-JerseyLogo-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 45,
      title: "Reign Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/111-Black+Crop+Top-JerseyLogo-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/111-Black+Crop+Top-JerseyLogo-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 46,
      title: "Reign Crown Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/112-+Womens+Purple+Sleeveless-+KatyCrown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/112-+Womens+Purple+Sleeveless-+KatyCrown-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/112-+Womens+White+Sleeveless-KatyCrown-Front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl: "reign/112-Womens+Black+Sleeveless-KatyCrown-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Purple", "White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 47,
      title: "Reign Crown Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/113-+White+Sleeveless-+Texas+Katy+Crown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/113-+White+Sleeveless-+Texas+Katy+Crown-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/113-+Black+Sleeveless-+Katy+Crown-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 48,
      title: "Reign Crown Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/114-BlackCropTop-Katy+Crown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/114-BlackCropTop-Katy+Crown-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 49,
      title: "Fancy Reign Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/115-+Womens+White+Sleeveless-+Fancy-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/115-+Womens+White+Sleeveless-+Fancy-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/115-+Womens+Black+Sleeveless-+Fancy-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 50,
      title: "Fancy Reign Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/116-+Black+Sleeveless-+Fancy-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/116-+Black+Sleeveless-+Fancy-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl: "reign/116-+White+Sleeveless-+Fancy-Front.png",
          color: "White",
        },
      ],
      sizes: sizes,
      colors: ["Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 51,
      title: "Fancy Reign Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/117-+Black+Crop-+Fancy-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/117-+Black+Crop-+Fancy-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 52,
      title: "Reign Mom Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/118-Womens+Purple+Sleeveless-Reign+Mom-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/118-Womens+Purple+Sleeveless-Reign+Mom-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl: "reign/118-Womens+Black+Sleeveless-Reign+Mom-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Purple", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 53,
      title: "Reign Dad Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/119-Womens+Black+Sleeveless-Reign+Dad-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/119-Womens+Black+Sleeveless-Reign+Dad-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 54,
      title: "Reign Mom Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/120-BlackCropTop-Reign+Mom-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/120-BlackCropTop-Reign+Mom-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 55,
      title: "Reign On Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/121-Womens+Black+Sleeveless-ReignOn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/121-Womens+Black+Sleeveless-ReignOn-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 56,
      title: "Reign On Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/122-Black+Sleeveless-ReignOn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/122-Black+Sleeveless-ReignOn-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 57,
      title: "Reign On Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/123-Black+Crop-ReignOn-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/123-Black+Crop-ReignOn-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 58,
      title: "Long May She Reign Crown Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image:
        "reign/124-+Womens+Purple+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/124-+Womens+Purple+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl:
            "reign/124-+Womens+White+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl:
            "reign/124-+Womens+Black+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Purple", "White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 59,
      title: "Long May She Reign Crown Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/125-+White+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/125-+White+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl:
            "reign/125-+Black+Sleeveless-+Long+May+She+Reign+Crown-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 60,
      title: "Long May She Reign Crown Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/126-BlackCropTop-Long+May+She+Reign+Crown-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/126-BlackCropTop-Long+May+She+Reign+Crown-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 61,
      title: "Long May She Reign Batter Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image:
        "reign/127-+Womens+White+Sleeveless-+Long+May+She+Reign+Batter-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/127-+Womens+White+Sleeveless-+Long+May+She+Reign+Batter-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl:
            "reign/127-+Womens+Black+Sleeveless-+Long+May+She+Reign+Batter-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 62,
      title: "Long May She Reign Batter Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/128-+Black+Sleeveless-+Long+May+She+Reign+Batter-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/128-+Black+Sleeveless-+Long+May+She+Reign+Batter-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl:
            "reign/128-+White+Sleeveless-+Long+May+She+Reign+Batter-Front.png",
          color: "White",
        },
      ],
      sizes: sizes,
      colors: ["Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 63,
      title: "Long May She Reign Batter Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/129-BlackCropTop-Long+May+She+Reign+Batter-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/129-BlackCropTop-Long+May+She+Reign+Batter-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 64,
      title: "Purple Reign Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/130-+Womens+Black+Sleeveless-+Purple+Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/130-+Womens+Black+Sleeveless-+Purple+Reign-Front.png",
          color: "Black",
        },
        {
          id: 1,
          imageUrl:
            "reign/130-+Womens+White+Sleeveless-+Purple+Reign-Front.png",
          color: "White",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black", "White"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 65,
      title: "Purple Reign Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/131-+White+Sleeveless-+Purple+Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/131-+White+Sleeveless-+Purple+Reign-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/131-+Black+Sleeveless-+Purple+Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 66,
      title: "Purple Reign Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/132-BlackCropTop-Purple+Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/132-BlackCropTop-Purple+Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
    {
      id: 67,
      title: "Custom Reign Sleeveless Womens Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/133-+Womens+Purple+Sleeveless-+Custom+Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl:
            "reign/133-+Womens+Purple+Sleeveless-+Custom+Reign-Front.png",
          color: "Purple",
        },
        {
          id: 1,
          imageUrl:
            "reign/133-+Womens+White+Sleeveless-+Custom+Reign-Front.png",
          color: "White",
        },
        {
          id: 2,
          imageUrl:
            "reign/133-+Womens+Black+Sleeveless-+Custom+Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Purple", "White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 68,
      title: "Custom Reign Sleeveless Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/134-+White+Sleeveless-+Custom+Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/134-+White+Sleeveless-+Custom+Reign-Front.png",
          color: "White",
        },
        {
          id: 1,
          imageUrl: "reign/134-+Black+Sleeveless-+Custom+Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: sizes,
      colors: ["White", "Black"],
      material: [DRIFIT],
      orders: [],
    },
    {
      id: 69,
      title: "Custom Reign Crop Top Shirt",
      isCustomizable: false,
      category: Categories.TSHIRTS,
      showBackSelection: false,
      price: 20.0,
      image: "reign/135-+Black+Crop-+Custom+Reign-Front.png",
      backImage: backMock,
      images: [
        {
          id: 0,
          imageUrl: "reign/135-+Black+Crop-+Custom+Reign-Front.png",
          color: "Black",
        },
      ],
      sizes: ["XS", "S", "M", "L", "XL", "2XL"],
      colors: ["Black"],
      material: ["Cotton"],
      orders: [],
    },
  ],
};
